-- ==========================================
-- GROWORGS PLATFORM SCHEMA (PostgreSQL)
-- Hand-written for the PostgreSQL migration (Phase 4) -- NOT a
-- mechanical translation of the old MySQL DDL. Consolidates what
-- were originally three separate incremental MySQL scripts
-- (_setup_platform_db.js, _migrate_add_subscriptions.js,
-- _setup_demo_requests_table.js) into the single final schema those
-- three scripts collectively produced, cross-checked against every
-- runtime services/*.js query that reads or writes these tables
-- (platformUserService.js, platformCompanyService.js,
-- subscriptionPlanService.js, demoRequestService.js) so every column
-- here is one the application actually uses -- nothing invented,
-- nothing missing.
--
-- Lives in the SAME PostgreSQL database as the tenant schema
-- (reinsteins_crm) -- PLATFORM_DB_NAME and DB_NAME are the same
-- value in this deployment's .env, so this is the intended
-- architecture, not a workaround. This file only ever adds the 4
-- platform tables below; it never touches any of the 37 existing
-- tenant tables.
--
-- Idempotent: every statement is safe to re-run. Applied by
-- server/_setup_platform_db.js, which also seeds the 5 default
-- subscription plans via ON CONFLICT DO NOTHING.
-- ==========================================

CREATE TABLE IF NOT EXISTS "platform_users" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(255) NOT NULL,
  "email" varchar(255) NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "role" varchar NOT NULL DEFAULT 'platform_owner' CHECK ("role" IN ('platform_owner')),
  "status" varchar NOT NULL DEFAULT 'active' CHECK ("status" IN ('active', 'inactive')),
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_platform_users_email" UNIQUE ("email")
);

CREATE TABLE IF NOT EXISTS "subscription_plans" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(100) NOT NULL,
  "slug" varchar(60) NOT NULL,
  "description" text,
  "status" varchar NOT NULL DEFAULT 'active' CHECK ("status" IN ('active', 'inactive')),
  "employee_limit" integer DEFAULT NULL,
  "storage_limit_mb" integer DEFAULT NULL,
  "features" jsonb DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_subscription_plans_slug" UNIQUE ("slug")
);

-- company_slug/status/access_type/tenant_db_name are the original
-- Phase 2A columns; plan_id through subscription_expires_at are the
-- Phase 8 additive subscription columns (originally added via
-- separate ALTER TABLE statements in _migrate_add_subscriptions.js
-- -- created here directly as part of one CREATE TABLE since this is
-- a from-scratch bootstrap, not a live-data migration).
CREATE TABLE IF NOT EXISTS "companies" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "company_name" varchar(255) NOT NULL,
  "company_slug" varchar(100) NOT NULL,
  "status" varchar NOT NULL DEFAULT 'pending' CHECK ("status" IN ('active', 'suspended', 'pending')),
  "access_type" varchar NOT NULL DEFAULT 'trial' CHECK ("access_type" IN ('complimentary', 'trial', 'paid')),
  "plan_id" integer DEFAULT NULL,
  "subscription_status" varchar NOT NULL DEFAULT 'active' CHECK ("subscription_status" IN ('active', 'trial', 'expired', 'cancelled')),
  "trial_ends_at" timestamp DEFAULT NULL,
  "subscription_started_at" timestamp DEFAULT NULL,
  "subscription_expires_at" timestamp DEFAULT NULL,
  "tenant_db_name" varchar(64) DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_companies_slug" UNIQUE ("company_slug")
);

-- MySQL's default FK reference option is RESTRICT -- matched here
-- explicitly so a plan with companies still assigned to it can never
-- be deleted (subscriptionPlanService.js also never exposes a
-- delete operation at the application layer; this is the
-- database-level backstop the original migration's comment
-- describes).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_companies_plan_id'
  ) THEN
    ALTER TABLE "companies"
      ADD CONSTRAINT "fk_companies_plan_id"
      FOREIGN KEY ("plan_id") REFERENCES "subscription_plans" ("id")
      ON DELETE RESTRICT;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "fk_companies_plan_id" ON "companies" ("plan_id");

-- Deliberately its own table, not a repurposed corner of `companies`
-- -- a demo request is a sales lead, not a company. The email CHECK
-- pattern is standard SQL LIKE syntax (not MySQL-specific) and is
-- carried over unchanged from the original MySQL definition.
CREATE TABLE IF NOT EXISTS "demo_requests" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(150) NOT NULL,
  "company_name" varchar(255) NOT NULL,
  "email" varchar(255) NOT NULL,
  "phone" varchar(30) DEFAULT NULL,
  "employee_count" varchar(50) DEFAULT NULL,
  "message" text,
  "status" varchar NOT NULL DEFAULT 'new' CHECK ("status" IN ('new', 'contacted', 'closed')),
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "chk_demo_requests_email" CHECK ("email" LIKE '%_@__%.__%')
);

CREATE INDEX IF NOT EXISTS "idx_demo_requests_status" ON "demo_requests" ("status");
CREATE INDEX IF NOT EXISTS "idx_demo_requests_created_at" ON "demo_requests" ("created_at");

-- ==========================================
-- PHASE 10-14 ADDITIONS (payments, subscription lifecycle
-- automation, billing contacts + email delivery, security
-- hardening) -- merged in alongside this file's original PostgreSQL
-- migration (Phase 4). Originally built and tested against MySQL as
-- five separate incremental scripts (_migrate_add_payments.js,
-- _migrate_add_plan_pricing.js, _migrate_add_subscription_lifecycle.js,
-- _migrate_add_email_billing.js, _migrate_add_security_hardening.js --
-- all left in place, unconverted, as historical record; do not run
-- them against this database). Translated to this file's PostgreSQL
-- conventions (varchar+CHECK instead of ENUM, GENERATED BY DEFAULT AS
-- IDENTITY instead of AUTO_INCREMENT, jsonb instead of JSON, a DO $$
-- block per FK constraint) rather than mechanically ported, matching
-- how the original 4 tables above were handled.
--
-- Idempotent, same guarantee as the rest of this file: every
-- statement is safe to re-run, including against a database that
-- already has some but not all of these changes applied.
-- ==========================================

-- ---------- Phase 12: grace period ----------
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "grace_period_ends_at" timestamp DEFAULT NULL;

-- ---------- Phase 13: billing contact (platform-level SaaS
-- metadata, distinct from any tenant employee data) ----------
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "billing_contact_name" varchar(255) DEFAULT NULL;
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "billing_contact_email" varchar(255) DEFAULT NULL;
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "billing_contact_phone" varchar(30) DEFAULT NULL;

-- ---------- Phase 11: plan pricing (nullable -- NULL means "no
-- price set yet", not zero; every pre-existing plan keeps working
-- unchanged) ----------
ALTER TABLE "subscription_plans" ADD COLUMN IF NOT EXISTS "monthly_price" numeric(10,2) DEFAULT NULL;
ALTER TABLE "subscription_plans" ADD COLUMN IF NOT EXISTS "yearly_price" numeric(10,2) DEFAULT NULL;
ALTER TABLE "subscription_plans" ADD COLUMN IF NOT EXISTS "trial_duration_days" integer DEFAULT NULL;

-- ---------- Phase 14: Platform Owner security hardening (account
-- lockout, TOTP 2FA, token versioning) -- platform_users only, see
-- the Phase 14 report for why this was not extended to every
-- tenant's own users table ----------
ALTER TABLE "platform_users" ADD COLUMN IF NOT EXISTS "failed_login_attempts" integer NOT NULL DEFAULT 0;
ALTER TABLE "platform_users" ADD COLUMN IF NOT EXISTS "locked_until" timestamp DEFAULT NULL;
ALTER TABLE "platform_users" ADD COLUMN IF NOT EXISTS "last_login_at" timestamp DEFAULT NULL;
ALTER TABLE "platform_users" ADD COLUMN IF NOT EXISTS "last_failed_login_at" timestamp DEFAULT NULL;
ALTER TABLE "platform_users" ADD COLUMN IF NOT EXISTS "totp_secret" varchar(255) DEFAULT NULL;
ALTER TABLE "platform_users" ADD COLUMN IF NOT EXISTS "totp_enabled" boolean NOT NULL DEFAULT FALSE;
ALTER TABLE "platform_users" ADD COLUMN IF NOT EXISTS "backup_codes" jsonb DEFAULT NULL;
ALTER TABLE "platform_users" ADD COLUMN IF NOT EXISTS "token_version" integer NOT NULL DEFAULT 0;

-- ---------- Phase 10/11: payments -- no card/CVV/bank data, only
-- provider-issued reference IDs. company_id/plan_id use ON DELETE
-- RESTRICT: a company or plan with real payment history can never be
-- deleted out from under its financial records. ----------
CREATE TABLE IF NOT EXISTS "payments" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "company_id" integer NOT NULL,
  "plan_id" integer NOT NULL,
  "amount" numeric(10,2) NOT NULL,
  "currency" varchar(3) NOT NULL DEFAULT 'INR',
  "billing_cycle" varchar NOT NULL CHECK ("billing_cycle" IN ('monthly', 'yearly', 'one_time')),
  "payment_status" varchar NOT NULL DEFAULT 'pending' CHECK ("payment_status" IN ('pending', 'paid', 'failed', 'refunded', 'cancelled')),
  "payment_provider" varchar(50) DEFAULT NULL,
  "provider_payment_id" varchar(255) DEFAULT NULL,
  "provider_order_id" varchar(255) DEFAULT NULL,
  "invoice_number" varchar(50) DEFAULT NULL,
  "notes" varchar(500) DEFAULT NULL,
  "paid_at" timestamp DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_payments_provider_payment_id" UNIQUE ("provider_payment_id"),
  CONSTRAINT "uq_payments_invoice_number" UNIQUE ("invoice_number")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_payments_company_id') THEN
    ALTER TABLE "payments" ADD CONSTRAINT "fk_payments_company_id" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE RESTRICT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_payments_plan_id') THEN
    ALTER TABLE "payments" ADD CONSTRAINT "fk_payments_plan_id" FOREIGN KEY ("plan_id") REFERENCES "subscription_plans" ("id") ON DELETE RESTRICT;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "idx_payments_company_id" ON "payments" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_payments_status" ON "payments" ("payment_status");
CREATE INDEX IF NOT EXISTS "idx_payments_paid_at" ON "payments" ("paid_at");

-- ---------- Phase 12: subscription_history -- append-only lifecycle
-- event log AND the durable dedupe store for reminder emails. ON
-- DELETE CASCADE (unlike payments' RESTRICT): operational history has
-- no financial/legal retention requirement the way payment records
-- do. ----------
CREATE TABLE IF NOT EXISTS "subscription_history" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "company_id" integer NOT NULL,
  "plan_id" integer DEFAULT NULL,
  "event_type" varchar(50) NOT NULL,
  "previous_status" varchar(20) DEFAULT NULL,
  "new_status" varchar(20) DEFAULT NULL,
  "previous_plan_id" integer DEFAULT NULL,
  "new_plan_id" integer DEFAULT NULL,
  "effective_at" timestamp DEFAULT NULL,
  "source" varchar(20) NOT NULL DEFAULT 'system',
  "reference_payment_id" integer DEFAULT NULL,
  "notes" varchar(500) DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_subhist_company_id') THEN
    ALTER TABLE "subscription_history" ADD CONSTRAINT "fk_subhist_company_id" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_subhist_payment_id') THEN
    ALTER TABLE "subscription_history" ADD CONSTRAINT "fk_subhist_payment_id" FOREIGN KEY ("reference_payment_id") REFERENCES "payments" ("id") ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "idx_subhist_company_id" ON "subscription_history" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_subhist_event_type" ON "subscription_history" ("event_type");
CREATE INDEX IF NOT EXISTS "idx_subhist_dedupe" ON "subscription_history" ("company_id", "event_type", "effective_at");

-- ---------- Phase 12: platform_audit_logs -- Platform Owner action
-- audit trail. platform_user_id/company_id are ON DELETE SET NULL,
-- not CASCADE: an audit record must survive even if its actor's
-- account or its target company is later deleted. ----------
CREATE TABLE IF NOT EXISTS "platform_audit_logs" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "platform_user_id" integer DEFAULT NULL,
  "action_type" varchar(50) NOT NULL,
  "target_type" varchar(30) NOT NULL,
  "target_id" integer DEFAULT NULL,
  "company_id" integer DEFAULT NULL,
  "metadata" jsonb DEFAULT NULL,
  "ip_address" varchar(45) DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_audit_platform_user_id') THEN
    ALTER TABLE "platform_audit_logs" ADD CONSTRAINT "fk_audit_platform_user_id" FOREIGN KEY ("platform_user_id") REFERENCES "platform_users" ("id") ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_audit_company_id') THEN
    ALTER TABLE "platform_audit_logs" ADD CONSTRAINT "fk_audit_company_id" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "idx_audit_action_type" ON "platform_audit_logs" ("action_type");
CREATE INDEX IF NOT EXISTS "idx_audit_company_id" ON "platform_audit_logs" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_audit_created_at" ON "platform_audit_logs" ("created_at");

-- ---------- Phase 12: platform_notifications -- durable, DB-backed
-- Platform Owner notification feed (distinct from the per-tenant
-- `notifications` table, which lives in each tenant database and has
-- no concept of cross-company platform events). ----------
CREATE TABLE IF NOT EXISTS "platform_notifications" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "platform_user_id" integer NOT NULL,
  "title" varchar(255) NOT NULL,
  "message" varchar(1000) NOT NULL,
  "type" varchar(50) NOT NULL DEFAULT 'general',
  "reference_type" varchar(30) DEFAULT NULL,
  "reference_id" integer DEFAULT NULL,
  "company_id" integer DEFAULT NULL,
  "is_read" boolean NOT NULL DEFAULT FALSE,
  "email_sent_at" timestamp DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_pnotif_platform_user_id') THEN
    ALTER TABLE "platform_notifications" ADD CONSTRAINT "fk_pnotif_platform_user_id" FOREIGN KEY ("platform_user_id") REFERENCES "platform_users" ("id") ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_pnotif_company_id') THEN
    ALTER TABLE "platform_notifications" ADD CONSTRAINT "fk_pnotif_company_id" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "idx_pnotif_owner_unread" ON "platform_notifications" ("platform_user_id", "is_read");
CREATE INDEX IF NOT EXISTS "idx_pnotif_created_at" ON "platform_notifications" ("created_at");

-- ---------- Phase 13: email_delivery_logs -- durable, honest email
-- delivery history. Stores template_data (small JSON of the values a
-- template needs), never the rendered HTML body -- enough to
-- regenerate the exact same email for a retry. company_id is ON
-- DELETE SET NULL: a delivery record survives its company's
-- deletion. ----------
CREATE TABLE IF NOT EXISTS "email_delivery_logs" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "company_id" integer DEFAULT NULL,
  "recipient_email" varchar(255) DEFAULT NULL,
  "recipient_name" varchar(255) DEFAULT NULL,
  "email_type" varchar(50) NOT NULL,
  "subject" varchar(255) NOT NULL,
  "template_data" jsonb DEFAULT NULL,
  "status" varchar NOT NULL DEFAULT 'pending' CHECK ("status" IN ('pending', 'sent', 'failed', 'skipped')),
  "provider_message_id" varchar(255) DEFAULT NULL,
  "error_message" varchar(500) DEFAULT NULL,
  "retry_count" integer NOT NULL DEFAULT 0,
  "last_attempt_at" timestamp DEFAULT NULL,
  "sent_at" timestamp DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_emaillog_company_id') THEN
    ALTER TABLE "email_delivery_logs" ADD CONSTRAINT "fk_emaillog_company_id" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "idx_emaillog_company_id" ON "email_delivery_logs" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_emaillog_status" ON "email_delivery_logs" ("status");
CREATE INDEX IF NOT EXISTS "idx_emaillog_email_type" ON "email_delivery_logs" ("email_type");
CREATE INDEX IF NOT EXISTS "idx_emaillog_created_at" ON "email_delivery_logs" ("created_at");
