-- ==========================================
-- GROWORGS PLATFORM SCHEMA (PostgreSQL)
-- Hand-written for the PostgreSQL migration (Phase 4) -- NOT a
-- mechanical translation of the old MySQL DDL. Consolidates what
-- were originally three separate incremental MySQL scripts
-- (_setup_platform_db.js, _migrate_add_subscriptions.js,
-- _setup_demo_requests_table.js) into the single final schema those
-- three scripts collectively produced, cross-checked against every
-- runtime services/*.js query that reads or writes these tables
-- (platformUserService.js, platformCompanyService.js,
-- subscriptionPlanService.js, demoRequestService.js) so every column
-- here is one the application actually uses -- nothing invented,
-- nothing missing.
--
-- Lives in the SAME PostgreSQL database as the tenant schema
-- (reinsteins_crm) -- PLATFORM_DB_NAME and DB_NAME are the same
-- value in this deployment's .env, so this is the intended
-- architecture, not a workaround. This file only ever adds the 4
-- platform tables below; it never touches any of the 37 existing
-- tenant tables.
--
-- Idempotent: every statement is safe to re-run. Applied by
-- server/_setup_platform_db.js, which also seeds the 5 default
-- subscription plans via ON CONFLICT DO NOTHING.
-- ==========================================

CREATE TABLE IF NOT EXISTS "platform_users" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(255) NOT NULL,
  "email" varchar(255) NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "role" varchar NOT NULL DEFAULT 'platform_owner' CHECK ("role" IN ('platform_owner')),
  "status" varchar NOT NULL DEFAULT 'active' CHECK ("status" IN ('active', 'inactive')),
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_platform_users_email" UNIQUE ("email")
);

CREATE TABLE IF NOT EXISTS "subscription_plans" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(100) NOT NULL,
  "slug" varchar(60) NOT NULL,
  "description" text,
  "status" varchar NOT NULL DEFAULT 'active' CHECK ("status" IN ('active', 'inactive')),
  "employee_limit" integer DEFAULT NULL,
  "storage_limit_mb" integer DEFAULT NULL,
  "features" jsonb DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_subscription_plans_slug" UNIQUE ("slug")
);

-- company_slug/status/access_type/tenant_db_name are the original
-- Phase 2A columns; plan_id through subscription_expires_at are the
-- Phase 8 additive subscription columns (originally added via
-- separate ALTER TABLE statements in _migrate_add_subscriptions.js
-- -- created here directly as part of one CREATE TABLE since this is
-- a from-scratch bootstrap, not a live-data migration).
CREATE TABLE IF NOT EXISTS "companies" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "company_name" varchar(255) NOT NULL,
  "company_slug" varchar(100) NOT NULL,
  "status" varchar NOT NULL DEFAULT 'pending' CHECK ("status" IN ('active', 'suspended', 'pending')),
  "access_type" varchar NOT NULL DEFAULT 'trial' CHECK ("access_type" IN ('complimentary', 'trial', 'paid')),
  "plan_id" integer DEFAULT NULL,
  "subscription_status" varchar NOT NULL DEFAULT 'active' CHECK ("subscription_status" IN ('active', 'trial', 'expired', 'cancelled')),
  "trial_ends_at" timestamp DEFAULT NULL,
  "subscription_started_at" timestamp DEFAULT NULL,
  "subscription_expires_at" timestamp DEFAULT NULL,
  "tenant_db_name" varchar(64) DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_companies_slug" UNIQUE ("company_slug")
);

-- MySQL's default FK reference option is RESTRICT -- matched here
-- explicitly so a plan with companies still assigned to it can never
-- be deleted (subscriptionPlanService.js also never exposes a
-- delete operation at the application layer; this is the
-- database-level backstop the original migration's comment
-- describes).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_companies_plan_id'
  ) THEN
    ALTER TABLE "companies"
      ADD CONSTRAINT "fk_companies_plan_id"
      FOREIGN KEY ("plan_id") REFERENCES "subscription_plans" ("id")
      ON DELETE RESTRICT;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "fk_companies_plan_id" ON "companies" ("plan_id");

-- Deliberately its own table, not a repurposed corner of `companies`
-- -- a demo request is a sales lead, not a company. The email CHECK
-- pattern is standard SQL LIKE syntax (not MySQL-specific) and is
-- carried over unchanged from the original MySQL definition.
CREATE TABLE IF NOT EXISTS "demo_requests" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(150) NOT NULL,
  "company_name" varchar(255) NOT NULL,
  "email" varchar(255) NOT NULL,
  "phone" varchar(30) DEFAULT NULL,
  "employee_count" varchar(50) DEFAULT NULL,
  "message" text,
  "status" varchar NOT NULL DEFAULT 'new' CHECK ("status" IN ('new', 'contacted', 'closed')),
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "chk_demo_requests_email" CHECK ("email" LIKE '%_@__%.__%')
);

CREATE INDEX IF NOT EXISTS "idx_demo_requests_status" ON "demo_requests" ("status");
CREATE INDEX IF NOT EXISTS "idx_demo_requests_created_at" ON "demo_requests" ("created_at");
