-- ==========================================
-- GROWORGS CANONICAL TENANT SCHEMA (Phase 2C)
-- Generated 2026-09-03T10:54:20.156Z via SHOW CREATE TABLE
-- against the live tenant database "reinsteins_workhub".
-- Source table count: 37
--
-- This file contains STRUCTURE ONLY -- no rows, no business
-- data. It is applied verbatim to a freshly created, empty
-- tenant database by tenantProvisioningService.js.
--
-- Regenerate with: node _generate_tenant_schema.js
-- ==========================================

CREATE TABLE "attendance" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "login_time" timestamp(6) NOT NULL,
  "logout_time" timestamp(6) DEFAULT NULL,
  "work_duration_seconds" bigint DEFAULT NULL,
  "status" varchar NOT NULL DEFAULT 'working' CHECK ("status" IN ('working', 'break', 'completed')),
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "break_start_time" timestamp(6) DEFAULT NULL,
  "total_break_seconds" int NOT NULL DEFAULT '0',
  PRIMARY KEY ("id")
);

CREATE TABLE "chat_attachments" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "message_id" bigint NOT NULL,
  "original_name" varchar(255) NOT NULL,
  "stored_name" varchar(255) NOT NULL,
  "file_type" varchar(100) NOT NULL,
  "file_size" bigint NOT NULL,
  "file_path" varchar(500) NOT NULL,
  "uploaded_by" integer NOT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE "conversation_members" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "conversation_id" bigint NOT NULL,
  "user_id" integer NOT NULL,
  "joined_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_read_at" timestamp NULL DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "unique_conversation_member" UNIQUE ("conversation_id","user_id")
);

CREATE TABLE "conversations" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "conversation_type" varchar NOT NULL DEFAULT 'private' CHECK ("conversation_type" IN ('private', 'group')),
  "name" varchar(150) DEFAULT NULL,
  "created_by" integer NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE "departments" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(150) NOT NULL,
  "code" varchar(20) NOT NULL,
  "description" text,
  "department_head_id" integer DEFAULT NULL,
  "status" varchar NOT NULL DEFAULT 'active' CHECK ("status" IN ('active', 'inactive')),
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "organization_id" integer DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_departments_code" UNIQUE ("code")
);

CREATE TABLE "designations" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "title" varchar(100) NOT NULL,
  "department_id" integer DEFAULT NULL,
  "status" varchar NOT NULL DEFAULT 'active' CHECK ("status" IN ('active', 'inactive')),
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "organization_id" integer DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_designations_title" UNIQUE ("title")
);

CREATE TABLE "employment_history" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "employment_type" varchar NOT NULL DEFAULT 'employee' CHECK ("employment_type" IN ('employee', 'intern')),
  "identifier" varchar(30) DEFAULT NULL,
  "designation" varchar(100) DEFAULT NULL,
  "start_date" date NOT NULL,
  "end_date" date DEFAULT NULL,
  "employment_status" varchar NOT NULL DEFAULT 'active' CHECK ("employment_status" IN ('active', 'inactive', 'resigned', 'terminated', 'retired', 'completed', 'discontinued', 'converted')),
  "notes" text,
  "exit_reason" text,
  "exit_notes" text,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE "epics" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "project_id" integer NOT NULL,
  "epic_code" varchar(20) DEFAULT NULL,
  "title" varchar(255) NOT NULL,
  "description" text,
  "owner_id" integer DEFAULT NULL,
  "created_by" integer NOT NULL,
  "priority" varchar NOT NULL DEFAULT 'Medium' CHECK ("priority" IN ('Low', 'Medium', 'High', 'Critical')),
  "status" varchar NOT NULL DEFAULT 'new' CHECK ("status" IN ('new', 'active', 'on_hold', 'completed', 'cancelled')),
  "start_date" date DEFAULT NULL,
  "due_date" date DEFAULT NULL,
  "deleted_at" timestamp DEFAULT NULL,
  "deleted_by" integer DEFAULT NULL,
  "deleted_batch_id" uuid DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_epics_code" UNIQUE ("epic_code")
);

CREATE TABLE "features" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "project_id" integer NOT NULL,
  "epic_id" integer DEFAULT NULL,
  "feature_code" varchar(20) DEFAULT NULL,
  "title" varchar(255) NOT NULL,
  "description" text,
  "owner_id" integer DEFAULT NULL,
  "created_by" integer NOT NULL,
  "priority" varchar NOT NULL DEFAULT 'Medium' CHECK ("priority" IN ('Low', 'Medium', 'High', 'Critical')),
  "status" varchar NOT NULL DEFAULT 'new' CHECK ("status" IN ('new', 'active', 'on_hold', 'completed', 'cancelled')),
  "start_date" date DEFAULT NULL,
  "due_date" date DEFAULT NULL,
  "deleted_at" timestamp DEFAULT NULL,
  "deleted_by" integer DEFAULT NULL,
  "deleted_batch_id" uuid DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_features_code" UNIQUE ("feature_code")
);

CREATE TABLE "leave_requests" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "manager_id" integer DEFAULT NULL,
  "leave_type" varchar  CHECK ("leave_type" IN ('casual', 'sick', 'earned', 'unpaid', 'other')) NOT NULL,
  "from_date" date NOT NULL,
  "to_date" date NOT NULL,
  "reason" text NOT NULL,
  "status" varchar NOT NULL DEFAULT 'pending_final' CHECK ("status" IN ('pending_manager', 'pending_final', 'manager_rejected', 'approved', 'rejected', 'cancelled')),
  "manager_decision" varchar DEFAULT NULL CHECK ("manager_decision" IN ('approved', 'rejected')),
  "manager_comment" text,
  "manager_decided_at" timestamp NULL DEFAULT NULL,
  "admin_comment" text,
  "final_decided_by" integer DEFAULT NULL,
  "final_decided_at" timestamp NULL DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE "meeting_message_attachments" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "message_id" integer NOT NULL,
  "original_name" varchar(255) NOT NULL,
  "stored_name" varchar(255) NOT NULL,
  "file_type" varchar(150) NOT NULL,
  "file_size" int NOT NULL,
  "file_path" varchar(500) NOT NULL,
  "uploaded_by" integer NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE "meeting_messages" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "meeting_id" integer NOT NULL,
  "sender_id" integer NOT NULL,
  "message_text" text NOT NULL,
  "message_type" varchar NOT NULL DEFAULT 'text' CHECK ("message_type" IN ('text', 'image', 'file')),
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE "meeting_participants" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "meeting_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "role" varchar NOT NULL DEFAULT 'participant' CHECK ("role" IN ('host', 'co_host', 'presenter', 'participant')),
  "status" varchar NOT NULL DEFAULT 'waiting' CHECK ("status" IN ('waiting', 'admitted', 'joined', 'left', 'removed', 'rejected')),
  "invited_by" integer DEFAULT NULL,
  "joined_at" timestamp DEFAULT NULL,
  "left_at" timestamp DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_meeting_participant" UNIQUE ("meeting_id","user_id")
);

CREATE TABLE "meetings" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "meeting_code" varchar(20) NOT NULL,
  "title" varchar(255) NOT NULL,
  "description" text,
  "host_id" integer NOT NULL,
  "meeting_type" varchar NOT NULL DEFAULT 'scheduled' CHECK ("meeting_type" IN ('instant', 'scheduled')),
  "scheduled_date" date DEFAULT NULL,
  "start_time" time DEFAULT NULL,
  "end_time" time DEFAULT NULL,
  "password_hash" varchar(255) DEFAULT NULL,
  "allow_guest_join" boolean NOT NULL DEFAULT TRUE,
  "waiting_room_enabled" boolean NOT NULL DEFAULT FALSE,
  "require_host_approval" boolean NOT NULL DEFAULT FALSE,
  "settings" json DEFAULT NULL,
  "status" varchar NOT NULL DEFAULT 'scheduled' CHECK ("status" IN ('scheduled', 'live', 'ended', 'cancelled')),
  "is_locked" boolean NOT NULL DEFAULT FALSE,
  "actual_start_time" timestamp DEFAULT NULL,
  "actual_end_time" timestamp DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_meetings_code" UNIQUE ("meeting_code")
);

CREATE TABLE "messages" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "conversation_id" bigint NOT NULL,
  "sender_id" integer NOT NULL,
  "message_text" text NOT NULL,
  "message_type" varchar NOT NULL DEFAULT 'text' CHECK ("message_type" IN ('text', 'image', 'file')),
  "is_deleted" boolean NOT NULL DEFAULT FALSE,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE "notifications" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "title" varchar(255) NOT NULL,
  "message" text NOT NULL,
  "type" varchar(50) DEFAULT 'general',
  "reference_type" varchar(30) DEFAULT NULL,
  "reference_id" integer DEFAULT NULL,
  "is_read" boolean DEFAULT FALSE,
  "email_sent_at" timestamp NULL DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE "organization_history" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "change_type" varchar  CHECK ("change_type" IN ('department', 'designation', 'reporting_manager', 'system_access', 'department_head')) NOT NULL,
  "old_value" varchar(255) DEFAULT NULL,
  "new_value" varchar(255) DEFAULT NULL,
  "changed_by" integer NOT NULL,
  "changed_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE "organization_members" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "organization_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "added_by" integer DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_om_user" UNIQUE ("user_id")
);

CREATE TABLE "organizations" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(255) NOT NULL,
  "description" text,
  "status" varchar NOT NULL DEFAULT 'active' CHECK ("status" IN ('active', 'inactive')),
  "created_by" integer DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE "project_activity" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "project_id" integer NOT NULL,
  "actor_id" integer NOT NULL,
  "activity_type" varchar  CHECK ("activity_type" IN ('member_added', 'member_removed', 'member_group_changed', 'permission_changed')) NOT NULL,
  "target_user_id" integer DEFAULT NULL,
  "details" text,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE "project_members" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "project_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "security_group_id" integer NOT NULL,
  "added_by" integer NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_project_member" UNIQUE ("project_id","user_id")
);

CREATE TABLE "project_permissions" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "security_group_id" integer NOT NULL,
  "project_id" integer DEFAULT NULL,
  "permission_key" varchar(64) NOT NULL,
  "value" varchar NOT NULL DEFAULT 'not_set' CHECK ("value" IN ('allow', 'deny', 'not_set')),
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE "project_security_groups" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "project_id" integer DEFAULT NULL,
  "name" varchar(100) NOT NULL,
  "description" varchar(255) DEFAULT NULL,
  "is_default" boolean NOT NULL DEFAULT FALSE,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE "projects" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(255) NOT NULL,
  "description" text,
  "owner_id" integer DEFAULT NULL,
  "created_by" integer NOT NULL,
  "status" varchar NOT NULL DEFAULT 'planning' CHECK ("status" IN ('planning', 'active', 'on_hold', 'completed', 'cancelled')),
  "priority" varchar NOT NULL DEFAULT 'Medium' CHECK ("priority" IN ('Low', 'Medium', 'High', 'Critical')),
  "start_date" date DEFAULT NULL,
  "due_date" date DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "organization_id" integer DEFAULT NULL,
  PRIMARY KEY ("id")
);

-- ==========================================
-- SHIFT SCHEDULE (Phase 17b)
--
-- No company_id/tenant_id column here, matching every other table in
-- this file (users, attendance, departments, designations, ...):
-- tenant isolation in this codebase is enforced by giving each
-- company its OWN database (see tenantProvisioningService.js), not by
-- a shared table filtered on a tenant column -- a row in THIS
-- database already belongs to exactly one company by construction.
--
-- Deliberately no UNIQUE(user_id, shift_date): a normal week only
-- ever has one row per employee per day (enforced at the application
-- layer in shiftScheduleController.js, which checks for an existing
-- row before creating a new one), but leaving the schema itself
-- unconstrained means a future split-shift phase (e.g. a morning row
-- and an evening row for the same employee/day) needs no migration.
-- ==========================================

CREATE TABLE "shift_schedule_history" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "shift_schedule_id" integer DEFAULT NULL,
  "user_id" integer DEFAULT NULL,
  "action" varchar NOT NULL CHECK ("action" IN ('created', 'updated', 'deleted')),
  "old_value" json DEFAULT NULL,
  "new_value" json DEFAULT NULL,
  "changed_by" integer DEFAULT NULL,
  "changed_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE "shift_schedules" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "shift_date" date NOT NULL,
  "status" varchar NOT NULL DEFAULT 'working' CHECK ("status" IN ('working', 'off', 'leave')),
  "start_time" time DEFAULT NULL,
  "end_time" time DEFAULT NULL,
  "notes" text,
  "created_by" integer DEFAULT NULL,
  "updated_by" integer DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

-- ==========================================
-- SOP LIBRARY (Phase 17c)
--
-- No company_id column, same reasoning as shift_schedules above --
-- tenant isolation is the tenant's own separate database, not a
-- shared-table filter.
-- ==========================================

CREATE TABLE "sops" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "title" varchar(255) NOT NULL,
  "original_filename" varchar(255) NOT NULL,
  "stored_filename" varchar(255) NOT NULL,
  "file_path" varchar(500) NOT NULL,
  "file_size" bigint NOT NULL,
  "mime_type" varchar(100) NOT NULL,
  "uploaded_by" integer DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE "sprints" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "project_id" integer NOT NULL,
  "name" varchar(100) NOT NULL,
  "goal" text,
  "start_date" date DEFAULT NULL,
  "end_date" date DEFAULT NULL,
  "status" varchar NOT NULL DEFAULT 'planning' CHECK ("status" IN ('planning', 'active', 'completed')),
  "created_by" integer NOT NULL,
  "deleted_at" timestamp DEFAULT NULL,
  "deleted_by" integer DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "active_marker" integer GENERATED ALWAYS AS (CASE WHEN "status" = 'active' THEN 1 ELSE NULL END) STORED,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_sprint_name_per_project" UNIQUE ("project_id","name"),
  CONSTRAINT "uq_one_active_sprint_per_project" UNIQUE ("project_id","active_marker"),


  CONSTRAINT "chk_sprint_dates" CHECK ((("end_date" is null) or ("start_date" is null) or ("end_date" >= "start_date")))
);

CREATE TABLE "tags" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(50) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uniq_tag_name" UNIQUE ("name")
);

CREATE TABLE "task_activity" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "task_id" integer NOT NULL,
  "author_id" integer NOT NULL,
  "activity_type" varchar NOT NULL DEFAULT 'comment' CHECK ("activity_type" IN ('comment', 'work_update', 'status_change', 'system')),
  "body" text,
  "progress_snapshot" int DEFAULT NULL,
  "old_status" varchar(30) DEFAULT NULL,
  "new_status" varchar(30) DEFAULT NULL,
  "is_edited" boolean NOT NULL DEFAULT FALSE,
  "is_deleted" boolean NOT NULL DEFAULT FALSE,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE "task_assignments" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "task_id" integer NOT NULL,
  "assigned_by" integer NOT NULL,
  "assigned_to" integer NOT NULL,
  "remarks" text,
  "assigned_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE "task_attachments" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "activity_id" integer NOT NULL,
  "original_name" varchar(255) NOT NULL,
  "stored_name" varchar(255) NOT NULL,
  "file_type" varchar(100) NOT NULL,
  "file_size" bigint NOT NULL,
  "file_path" varchar(500) NOT NULL,
  "uploaded_by" integer NOT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE "task_mentions" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "activity_id" integer NOT NULL,
  "mentioned_user_id" integer NOT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE "task_tags" (
  "task_id" integer NOT NULL,
  "tag_id" integer NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("task_id","tag_id")
);

CREATE TABLE "task_transfer_requests" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "task_id" integer NOT NULL,
  "requested_by" integer NOT NULL,
  "current_assignee_id" integer NOT NULL,
  "proposed_assignee_id" integer NOT NULL,
  "reason" text,
  "approver_id" integer DEFAULT NULL,
  "status" varchar NOT NULL DEFAULT 'pending' CHECK ("status" IN ('pending', 'approved', 'rejected')),
  "decided_by" integer DEFAULT NULL,
  "decided_at" timestamp NULL DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE "task_work_logs" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "task_id" integer NOT NULL,
  "employee_id" integer NOT NULL,
  "work_description" text NOT NULL,
  "hours_worked" decimal(5,2) NOT NULL,
  "progress" int NOT NULL,
  "status" varchar  CHECK ("status" IN ('New', 'Assigned', 'In Progress', 'On Hold', 'Review', 'Completed', 'Closed')) NOT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE "tasks" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "task_number" varchar(20) DEFAULT NULL,
  "user_id" integer NOT NULL,
  "project_id" integer DEFAULT NULL,
  "user_story_id" integer DEFAULT NULL,
  "sprint_id" integer DEFAULT NULL,
  "assigned_to" integer DEFAULT NULL,
  "assigned_by" integer DEFAULT NULL,
  "task_title" varchar(255) NOT NULL,
  "task_description" text NOT NULL,
  "priority" varchar DEFAULT 'Medium' CHECK ("priority" IN ('Low', 'Medium', 'High', 'Critical')),
  "start_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  "completed_time" timestamp(6) DEFAULT NULL,
  "admin_closed_time" timestamp DEFAULT NULL,
  "created_at" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  "updated_at" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  "status" varchar NOT NULL DEFAULT 'in_progress' CHECK ("status" IN ('backlog', 'todo', 'in_progress', 'pending_review', 'closed')),
  "due_date" date DEFAULT NULL,
  "progress" int DEFAULT '0',
  "estimated_hours" decimal(5,2) DEFAULT NULL,
  "actual_hours" decimal(5,2) DEFAULT NULL,
  "tags" varchar(255) DEFAULT NULL,
  "work_started_at" timestamp DEFAULT NULL,
  "current_working" boolean DEFAULT FALSE,
  "admin_closed" boolean NOT NULL DEFAULT FALSE,
  "deleted_at" timestamp DEFAULT NULL,
  "deleted_by" integer DEFAULT NULL,
  "deleted_batch_id" uuid DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "user_stories" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "project_id" integer NOT NULL,
  "feature_id" integer DEFAULT NULL,
  "sprint_id" integer DEFAULT NULL,
  "story_code" varchar(20) DEFAULT NULL,
  "title" varchar(255) NOT NULL,
  "description" text,
  "owner_id" integer DEFAULT NULL,
  "created_by" integer NOT NULL,
  "priority" varchar NOT NULL DEFAULT 'Medium' CHECK ("priority" IN ('Low', 'Medium', 'High', 'Critical')),
  "status" varchar NOT NULL DEFAULT 'new' CHECK ("status" IN ('new', 'active', 'on_hold', 'completed', 'cancelled')),
  "start_date" date DEFAULT NULL,
  "due_date" date DEFAULT NULL,
  "tags" varchar(255) DEFAULT NULL,
  "deleted_at" timestamp DEFAULT NULL,
  "deleted_by" integer DEFAULT NULL,
  "deleted_batch_id" uuid DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_user_stories_code" UNIQUE ("story_code")
);

CREATE TABLE "users" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "employee_id" varchar(30) NOT NULL,
  "first_name" varchar(50) DEFAULT NULL,
  "last_name" varchar(50) DEFAULT NULL,
  "full_name" varchar(100) NOT NULL,
  "email" varchar(150) DEFAULT NULL,
  "phone" varchar(20) DEFAULT NULL,
  "address" text,
  "date_of_birth" date DEFAULT NULL,
  "designation" varchar(100) DEFAULT NULL,
  "department_id" integer DEFAULT NULL,
  "employment_status" varchar NOT NULL DEFAULT 'active' CHECK ("employment_status" IN ('active', 'inactive', 'resigned', 'terminated', 'retired', 'completed', 'discontinued', 'converted')),
  "joining_date" date DEFAULT NULL,
  "last_working_date" date DEFAULT NULL,
  "internship_end_date" date DEFAULT NULL,
  "mentor_id" integer DEFAULT NULL,
  "reporting_manager_id" integer DEFAULT NULL,
  "stipend" decimal(10,2) DEFAULT NULL,
  "exited_at" timestamp NULL DEFAULT NULL,
  "exit_reason" text,
  "exit_notes" text,
  "emergency_contact" varchar(20) DEFAULT NULL,
  "profile_photo" varchar(255) DEFAULT NULL,
  "password" varchar(255) NOT NULL,
  "role" varchar NOT NULL DEFAULT 'employee' CHECK ("role" IN ('admin', 'employee')),
  "system_access" varchar NOT NULL DEFAULT 'employee' CHECK ("system_access" IN ('super_admin', 'admin', 'executive', 'hr', 'department_head', 'manager', 'team_lead', 'employee')),
  "project_access_override" varchar DEFAULT NULL CHECK ("project_access_override" IN ('granted', 'revoked')),
  "project_access_level" varchar NOT NULL DEFAULT 'basic' CHECK ("project_access_level" IN ('stakeholder', 'basic')),
  "employment_type" varchar NOT NULL DEFAULT 'employee' CHECK ("employment_type" IN ('employee', 'intern')),
  "status" varchar NOT NULL DEFAULT 'pending' CHECK ("status" IN ('pending', 'active', 'inactive')),
  "last_login" timestamp DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "organization_id" integer DEFAULT NULL,
  -- Tenant-wide highest authority -- exactly one TRUE row per tenant,
  -- enforced by the partial unique index below (not just by
  -- convention, unlike project_security_groups.is_default). Set ONLY
  -- by tenantUserService.createFirstAdmin() and the one-off backfill
  -- migration for pre-existing tenants -- no API/route ever writes
  -- this column. Deliberately independent of role/system_access: the
  -- project permission engine (services/projectPermissionService.js)
  -- checks this flag alone, never role='admin' or
  -- system_access='super_admin', so granting/promoting a Super Admin
  -- can never accidentally grant this authority.
  "is_system_administrator" boolean NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id"),
  CONSTRAINT "employee_id" UNIQUE ("employee_id"),
  CONSTRAINT "email" UNIQUE ("email")
);

CREATE UNIQUE INDEX "uq_users_one_system_administrator" ON "users" ("is_system_administrator") WHERE "is_system_administrator" = TRUE;

CREATE TABLE "work_item_links" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "source_type" varchar  CHECK ("source_type" IN ('epic', 'feature', 'user_story', 'task')) NOT NULL,
  "source_id" integer NOT NULL,
  "target_type" varchar  CHECK ("target_type" IN ('epic', 'feature', 'user_story', 'task')) NOT NULL,
  "target_id" integer NOT NULL,
  "link_type" varchar  CHECK ("link_type" IN ('related', 'blocks')) NOT NULL,
  "project_id" integer NOT NULL,
  "created_by" integer NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uniq_work_item_link" UNIQUE ("source_type","source_id","target_type","target_id","link_type")
);


-- PostgreSQL foreign keys converted from MySQL
ALTER TABLE "attendance" ADD CONSTRAINT "fk_attendance_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "chat_attachments" ADD CONSTRAINT "fk_attachment_message" FOREIGN KEY ("message_id") REFERENCES "messages" ("id") ON DELETE CASCADE;
ALTER TABLE "chat_attachments" ADD CONSTRAINT "fk_attachment_user" FOREIGN KEY ("uploaded_by") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "conversation_members" ADD CONSTRAINT "fk_conversation_members_conversation" FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("id") ON DELETE CASCADE;
ALTER TABLE "conversation_members" ADD CONSTRAINT "fk_conversation_members_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "conversations" ADD CONSTRAINT "fk_conversations_created_by" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "departments" ADD CONSTRAINT "fk_departments_head" FOREIGN KEY ("department_head_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "departments" ADD CONSTRAINT "fk_departments_organization" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") ON DELETE SET NULL;
ALTER TABLE "designations" ADD CONSTRAINT "fk_designations_department" FOREIGN KEY ("department_id") REFERENCES "departments" ("id") ON DELETE SET NULL;
ALTER TABLE "designations" ADD CONSTRAINT "fk_designations_organization" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") ON DELETE SET NULL;
ALTER TABLE "employment_history" ADD CONSTRAINT "fk_employment_history_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "epics" ADD CONSTRAINT "fk_epics_created_by" FOREIGN KEY ("created_by") REFERENCES "users" ("id");
ALTER TABLE "epics" ADD CONSTRAINT "fk_epics_owner" FOREIGN KEY ("owner_id") REFERENCES "users" ("id");
ALTER TABLE "epics" ADD CONSTRAINT "fk_epics_project" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE;
ALTER TABLE "features" ADD CONSTRAINT "fk_features_created_by" FOREIGN KEY ("created_by") REFERENCES "users" ("id");
ALTER TABLE "features" ADD CONSTRAINT "fk_features_epic" FOREIGN KEY ("epic_id") REFERENCES "epics" ("id") ON DELETE SET NULL;
ALTER TABLE "features" ADD CONSTRAINT "fk_features_owner" FOREIGN KEY ("owner_id") REFERENCES "users" ("id");
ALTER TABLE "features" ADD CONSTRAINT "fk_features_project" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE;
ALTER TABLE "leave_requests" ADD CONSTRAINT "fk_leave_final_decided_by" FOREIGN KEY ("final_decided_by") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "leave_requests" ADD CONSTRAINT "fk_leave_manager" FOREIGN KEY ("manager_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "leave_requests" ADD CONSTRAINT "fk_leave_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "meeting_message_attachments" ADD CONSTRAINT "fk_meeting_msg_attachment_message" FOREIGN KEY ("message_id") REFERENCES "meeting_messages" ("id") ON DELETE CASCADE;
ALTER TABLE "meeting_message_attachments" ADD CONSTRAINT "fk_meeting_msg_attachment_uploader" FOREIGN KEY ("uploaded_by") REFERENCES "users" ("id");
ALTER TABLE "meeting_messages" ADD CONSTRAINT "fk_meeting_messages_meeting" FOREIGN KEY ("meeting_id") REFERENCES "meetings" ("id") ON DELETE CASCADE;
ALTER TABLE "meeting_messages" ADD CONSTRAINT "fk_meeting_messages_sender" FOREIGN KEY ("sender_id") REFERENCES "users" ("id");
ALTER TABLE "meeting_participants" ADD CONSTRAINT "fk_meeting_participants_invited_by" FOREIGN KEY ("invited_by") REFERENCES "users" ("id");
ALTER TABLE "meeting_participants" ADD CONSTRAINT "fk_meeting_participants_meeting" FOREIGN KEY ("meeting_id") REFERENCES "meetings" ("id") ON DELETE CASCADE;
ALTER TABLE "meeting_participants" ADD CONSTRAINT "fk_meeting_participants_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "meetings" ADD CONSTRAINT "fk_meetings_host" FOREIGN KEY ("host_id") REFERENCES "users" ("id");
ALTER TABLE "messages" ADD CONSTRAINT "fk_messages_conversation" FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("id") ON DELETE CASCADE;
ALTER TABLE "messages" ADD CONSTRAINT "fk_messages_sender" FOREIGN KEY ("sender_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "notifications" ADD CONSTRAINT "fk_notifications_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "organization_history" ADD CONSTRAINT "fk_org_history_changed_by" FOREIGN KEY ("changed_by") REFERENCES "users" ("id");
ALTER TABLE "organization_history" ADD CONSTRAINT "fk_org_history_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "organization_members" ADD CONSTRAINT "fk_om_added_by" FOREIGN KEY ("added_by") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "organization_members" ADD CONSTRAINT "fk_om_organization" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") ON DELETE CASCADE;
ALTER TABLE "organization_members" ADD CONSTRAINT "fk_om_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "organizations" ADD CONSTRAINT "fk_organizations_created_by" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "project_activity" ADD CONSTRAINT "fk_pa_actor" FOREIGN KEY ("actor_id") REFERENCES "users" ("id");
ALTER TABLE "project_activity" ADD CONSTRAINT "fk_pa_project" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE;
ALTER TABLE "project_activity" ADD CONSTRAINT "fk_pa_target" FOREIGN KEY ("target_user_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "project_members" ADD CONSTRAINT "fk_pm_added_by" FOREIGN KEY ("added_by") REFERENCES "users" ("id");
ALTER TABLE "project_members" ADD CONSTRAINT "fk_pm_group" FOREIGN KEY ("security_group_id") REFERENCES "project_security_groups" ("id");
ALTER TABLE "project_members" ADD CONSTRAINT "fk_pm_project" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE;
ALTER TABLE "project_members" ADD CONSTRAINT "fk_pm_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "project_permissions" ADD CONSTRAINT "fk_pp_group" FOREIGN KEY ("security_group_id") REFERENCES "project_security_groups" ("id") ON DELETE CASCADE;
ALTER TABLE "project_permissions" ADD CONSTRAINT "fk_pp_project" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE;
ALTER TABLE "project_security_groups" ADD CONSTRAINT "fk_psg_project" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE;
ALTER TABLE "projects" ADD CONSTRAINT "fk_projects_created_by" FOREIGN KEY ("created_by") REFERENCES "users" ("id");
ALTER TABLE "projects" ADD CONSTRAINT "fk_projects_organization" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") ON DELETE SET NULL;
ALTER TABLE "projects" ADD CONSTRAINT "fk_projects_owner" FOREIGN KEY ("owner_id") REFERENCES "users" ("id");
ALTER TABLE "shift_schedule_history" ADD CONSTRAINT "fk_ssh_shift" FOREIGN KEY ("shift_schedule_id") REFERENCES "shift_schedules" ("id") ON DELETE SET NULL;
ALTER TABLE "shift_schedule_history" ADD CONSTRAINT "fk_ssh_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "shift_schedule_history" ADD CONSTRAINT "fk_ssh_changed_by" FOREIGN KEY ("changed_by") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "shift_schedules" ADD CONSTRAINT "fk_shift_schedules_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "shift_schedules" ADD CONSTRAINT "fk_shift_schedules_created_by" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "shift_schedules" ADD CONSTRAINT "fk_shift_schedules_updated_by" FOREIGN KEY ("updated_by") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "sops" ADD CONSTRAINT "fk_sops_uploaded_by" FOREIGN KEY ("uploaded_by") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "sprints" ADD CONSTRAINT "fk_sprints_created_by" FOREIGN KEY ("created_by") REFERENCES "users" ("id");
ALTER TABLE "sprints" ADD CONSTRAINT "fk_sprints_project" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE;
ALTER TABLE "task_activity" ADD CONSTRAINT "fk_task_activity_author" FOREIGN KEY ("author_id") REFERENCES "users" ("id");
ALTER TABLE "task_activity" ADD CONSTRAINT "fk_task_activity_task" FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") ON DELETE CASCADE;
ALTER TABLE "task_assignments" ADD CONSTRAINT "fk_task_assignment_assigned_by" FOREIGN KEY ("assigned_by") REFERENCES "users" ("id");
ALTER TABLE "task_assignments" ADD CONSTRAINT "fk_task_assignment_assigned_to" FOREIGN KEY ("assigned_to") REFERENCES "users" ("id");
ALTER TABLE "task_assignments" ADD CONSTRAINT "fk_task_assignment_task" FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") ON DELETE CASCADE;
ALTER TABLE "task_attachments" ADD CONSTRAINT "fk_task_attachment_activity" FOREIGN KEY ("activity_id") REFERENCES "task_activity" ("id") ON DELETE CASCADE;
ALTER TABLE "task_attachments" ADD CONSTRAINT "fk_task_attachment_user" FOREIGN KEY ("uploaded_by") REFERENCES "users" ("id");
ALTER TABLE "task_mentions" ADD CONSTRAINT "fk_task_mention_activity" FOREIGN KEY ("activity_id") REFERENCES "task_activity" ("id") ON DELETE CASCADE;
ALTER TABLE "task_mentions" ADD CONSTRAINT "fk_task_mention_user" FOREIGN KEY ("mentioned_user_id") REFERENCES "users" ("id");
ALTER TABLE "task_tags" ADD CONSTRAINT "fk_task_tags_tag" FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") ON DELETE CASCADE;
ALTER TABLE "task_tags" ADD CONSTRAINT "fk_task_tags_task" FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") ON DELETE CASCADE;
ALTER TABLE "task_transfer_requests" ADD CONSTRAINT "fk_transfer_approver" FOREIGN KEY ("approver_id") REFERENCES "users" ("id");
ALTER TABLE "task_transfer_requests" ADD CONSTRAINT "fk_transfer_current_assignee" FOREIGN KEY ("current_assignee_id") REFERENCES "users" ("id");
ALTER TABLE "task_transfer_requests" ADD CONSTRAINT "fk_transfer_decided_by" FOREIGN KEY ("decided_by") REFERENCES "users" ("id");
ALTER TABLE "task_transfer_requests" ADD CONSTRAINT "fk_transfer_proposed_assignee" FOREIGN KEY ("proposed_assignee_id") REFERENCES "users" ("id");
ALTER TABLE "task_transfer_requests" ADD CONSTRAINT "fk_transfer_requested_by" FOREIGN KEY ("requested_by") REFERENCES "users" ("id");
ALTER TABLE "task_transfer_requests" ADD CONSTRAINT "fk_transfer_task" FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") ON DELETE CASCADE;
ALTER TABLE "task_work_logs" ADD CONSTRAINT "fk_worklog_employee" FOREIGN KEY ("employee_id") REFERENCES "users" ("id");
ALTER TABLE "task_work_logs" ADD CONSTRAINT "fk_worklog_task" FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") ON DELETE CASCADE;
ALTER TABLE "tasks" ADD CONSTRAINT "fk_tasks_project" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE SET NULL;
ALTER TABLE "tasks" ADD CONSTRAINT "fk_tasks_sprint" FOREIGN KEY ("sprint_id") REFERENCES "sprints" ("id") ON DELETE SET NULL;
ALTER TABLE "tasks" ADD CONSTRAINT "fk_tasks_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "tasks" ADD CONSTRAINT "fk_tasks_user_story" FOREIGN KEY ("user_story_id") REFERENCES "user_stories" ("id") ON DELETE SET NULL;
ALTER TABLE "user_stories" ADD CONSTRAINT "fk_user_stories_created_by" FOREIGN KEY ("created_by") REFERENCES "users" ("id");
ALTER TABLE "user_stories" ADD CONSTRAINT "fk_user_stories_feature" FOREIGN KEY ("feature_id") REFERENCES "features" ("id") ON DELETE SET NULL;
ALTER TABLE "user_stories" ADD CONSTRAINT "fk_user_stories_owner" FOREIGN KEY ("owner_id") REFERENCES "users" ("id");
ALTER TABLE "user_stories" ADD CONSTRAINT "fk_user_stories_project" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE;
ALTER TABLE "users" ADD CONSTRAINT "fk_users_department" FOREIGN KEY ("department_id") REFERENCES "departments" ("id") ON DELETE SET NULL;
ALTER TABLE "users" ADD CONSTRAINT "fk_users_mentor" FOREIGN KEY ("mentor_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "users" ADD CONSTRAINT "fk_users_organization" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") ON DELETE SET NULL;
ALTER TABLE "users" ADD CONSTRAINT "fk_users_reporting_manager" FOREIGN KEY ("reporting_manager_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "work_item_links" ADD CONSTRAINT "fk_wil_created_by" FOREIGN KEY ("created_by") REFERENCES "users" ("id");
ALTER TABLE "work_item_links" ADD CONSTRAINT "fk_wil_project" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE;

-- Recycle Bin (soft delete) -- who deleted each work item, and the
-- new Sprint<->User Story association (mirrors the existing
-- fk_tasks_sprint pattern; User Stories previously had no Sprint
-- association at all).
ALTER TABLE "epics" ADD CONSTRAINT "fk_epics_deleted_by" FOREIGN KEY ("deleted_by") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "features" ADD CONSTRAINT "fk_features_deleted_by" FOREIGN KEY ("deleted_by") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "user_stories" ADD CONSTRAINT "fk_user_stories_deleted_by" FOREIGN KEY ("deleted_by") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "user_stories" ADD CONSTRAINT "fk_user_stories_sprint" FOREIGN KEY ("sprint_id") REFERENCES "sprints" ("id") ON DELETE SET NULL;
ALTER TABLE "tasks" ADD CONSTRAINT "fk_tasks_deleted_by" FOREIGN KEY ("deleted_by") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "sprints" ADD CONSTRAINT "fk_sprints_deleted_by" FOREIGN KEY ("deleted_by") REFERENCES "users" ("id") ON DELETE SET NULL;


-- PostgreSQL indexes converted from MySQL KEY definitions
CREATE INDEX "idx_attendance_user_id" ON "attendance" ("user_id");
CREATE INDEX "idx_attendance_login_time" ON "attendance" ("login_time");
CREATE INDEX "idx_attendance_status" ON "attendance" ("status");
CREATE INDEX "fk_attachment_message" ON "chat_attachments" ("message_id");
CREATE INDEX "fk_attachment_user" ON "chat_attachments" ("uploaded_by");
CREATE INDEX "idx_conversation_members_user" ON "conversation_members" ("user_id");
CREATE INDEX "idx_conversations_updated_at" ON "conversations" ("updated_at");
CREATE INDEX "fk_conversations_created_by" ON "conversations" ("created_by");
CREATE INDEX "fk_departments_head" ON "departments" ("department_head_id");
CREATE INDEX "fk_departments_organization" ON "departments" ("organization_id");
CREATE INDEX "fk_designations_department" ON "designations" ("department_id");
CREATE INDEX "fk_designations_organization" ON "designations" ("organization_id");
CREATE INDEX "fk_employment_history_user" ON "employment_history" ("user_id");
CREATE INDEX "fk_epics_project" ON "epics" ("project_id");
CREATE INDEX "fk_epics_owner" ON "epics" ("owner_id");
CREATE INDEX "fk_epics_created_by" ON "epics" ("created_by");
CREATE INDEX "fk_features_project" ON "features" ("project_id");
CREATE INDEX "fk_features_epic" ON "features" ("epic_id");
CREATE INDEX "fk_features_owner" ON "features" ("owner_id");
CREATE INDEX "fk_features_created_by" ON "features" ("created_by");
CREATE INDEX "fk_leave_user" ON "leave_requests" ("user_id");
CREATE INDEX "fk_leave_final_decided_by" ON "leave_requests" ("final_decided_by");
CREATE INDEX "idx_leave_manager_status" ON "leave_requests" ("manager_id","status");
CREATE INDEX "fk_meeting_msg_attachment_message" ON "meeting_message_attachments" ("message_id");
CREATE INDEX "fk_meeting_msg_attachment_uploader" ON "meeting_message_attachments" ("uploaded_by");
CREATE INDEX "fk_meeting_messages_meeting" ON "meeting_messages" ("meeting_id");
CREATE INDEX "fk_meeting_messages_sender" ON "meeting_messages" ("sender_id");
CREATE INDEX "fk_meeting_participants_user" ON "meeting_participants" ("user_id");
CREATE INDEX "fk_meeting_participants_invited_by" ON "meeting_participants" ("invited_by");
CREATE INDEX "fk_meetings_host" ON "meetings" ("host_id");
CREATE INDEX "idx_messages_conversation_created" ON "messages" ("conversation_id","created_at");
CREATE INDEX "idx_messages_sender" ON "messages" ("sender_id");
CREATE INDEX "idx_notifications_user_id" ON "notifications" ("user_id");
CREATE INDEX "idx_notifications_is_read" ON "notifications" ("is_read");
CREATE INDEX "idx_notifications_reference" ON "notifications" ("reference_type","reference_id");
CREATE INDEX "idx_org_history_user" ON "organization_history" ("user_id");
CREATE INDEX "idx_org_history_changed_at" ON "organization_history" ("changed_at");
CREATE INDEX "fk_org_history_changed_by" ON "organization_history" ("changed_by");
CREATE INDEX "fk_om_organization" ON "organization_members" ("organization_id");
CREATE INDEX "fk_om_added_by" ON "organization_members" ("added_by");
CREATE INDEX "fk_organizations_created_by" ON "organizations" ("created_by");
CREATE INDEX "idx_project_activity_project" ON "project_activity" ("project_id","created_at");
CREATE INDEX "fk_pa_actor" ON "project_activity" ("actor_id");
CREATE INDEX "fk_pa_target" ON "project_activity" ("target_user_id");
CREATE INDEX "idx_project_members_user" ON "project_members" ("user_id");
CREATE INDEX "fk_pm_group" ON "project_members" ("security_group_id");
CREATE INDEX "fk_pm_added_by" ON "project_members" ("added_by");
CREATE INDEX "fk_pp_group" ON "project_permissions" ("security_group_id");
CREATE INDEX "fk_pp_project" ON "project_permissions" ("project_id");
CREATE INDEX "fk_psg_project" ON "project_security_groups" ("project_id");
CREATE INDEX "fk_projects_owner" ON "projects" ("owner_id");
CREATE INDEX "fk_projects_created_by" ON "projects" ("created_by");
CREATE INDEX "fk_projects_organization" ON "projects" ("organization_id");
CREATE INDEX "idx_shift_schedule_history_shift" ON "shift_schedule_history" ("shift_schedule_id");
CREATE INDEX "idx_shift_schedule_history_user" ON "shift_schedule_history" ("user_id");
CREATE INDEX "idx_shift_schedules_user_id" ON "shift_schedules" ("user_id");
CREATE INDEX "idx_shift_schedules_shift_date" ON "shift_schedules" ("shift_date");
CREATE INDEX "idx_shift_schedules_user_date" ON "shift_schedules" ("user_id", "shift_date");
CREATE INDEX "idx_sops_created_at" ON "sops" ("created_at");
CREATE INDEX "idx_sops_uploaded_by" ON "sops" ("uploaded_by");
CREATE INDEX "fk_sprints_project" ON "sprints" ("project_id");
CREATE INDEX "fk_sprints_created_by" ON "sprints" ("created_by");
CREATE INDEX "fk_task_activity_task" ON "task_activity" ("task_id");
CREATE INDEX "fk_task_activity_author" ON "task_activity" ("author_id");
CREATE INDEX "fk_task_assignment_task" ON "task_assignments" ("task_id");
CREATE INDEX "fk_task_assignment_assigned_by" ON "task_assignments" ("assigned_by");
CREATE INDEX "fk_task_assignment_assigned_to" ON "task_assignments" ("assigned_to");
CREATE INDEX "fk_task_attachment_activity" ON "task_attachments" ("activity_id");
CREATE INDEX "fk_task_attachment_user" ON "task_attachments" ("uploaded_by");
CREATE INDEX "fk_task_mention_activity" ON "task_mentions" ("activity_id");
CREATE INDEX "fk_task_mention_user" ON "task_mentions" ("mentioned_user_id");
CREATE INDEX "idx_task_tags_tag_id" ON "task_tags" ("tag_id");
CREATE INDEX "idx_transfer_task" ON "task_transfer_requests" ("task_id");
CREATE INDEX "idx_transfer_approver" ON "task_transfer_requests" ("approver_id","status");
CREATE INDEX "fk_transfer_requested_by" ON "task_transfer_requests" ("requested_by");
CREATE INDEX "fk_transfer_current_assignee" ON "task_transfer_requests" ("current_assignee_id");
CREATE INDEX "fk_transfer_proposed_assignee" ON "task_transfer_requests" ("proposed_assignee_id");
CREATE INDEX "fk_transfer_decided_by" ON "task_transfer_requests" ("decided_by");
CREATE INDEX "fk_worklog_task" ON "task_work_logs" ("task_id");
CREATE INDEX "fk_worklog_employee" ON "task_work_logs" ("employee_id");
CREATE INDEX "fk_tasks_user" ON "tasks" ("user_id");
CREATE INDEX "fk_tasks_project" ON "tasks" ("project_id");
CREATE INDEX "fk_tasks_user_story" ON "tasks" ("user_story_id");
CREATE INDEX "fk_tasks_sprint" ON "tasks" ("sprint_id");
CREATE INDEX "fk_user_stories_project" ON "user_stories" ("project_id");
CREATE INDEX "fk_user_stories_owner" ON "user_stories" ("owner_id");
CREATE INDEX "fk_user_stories_created_by" ON "user_stories" ("created_by");
CREATE INDEX "fk_user_stories_feature" ON "user_stories" ("feature_id");

-- Recycle Bin (soft delete) lookups + new Sprint<->User Story link
CREATE INDEX "idx_epics_deleted_at" ON "epics" ("deleted_at");
CREATE INDEX "idx_features_deleted_at" ON "features" ("deleted_at");
CREATE INDEX "idx_user_stories_deleted_at" ON "user_stories" ("deleted_at");
CREATE INDEX "fk_user_stories_sprint" ON "user_stories" ("sprint_id");
CREATE INDEX "idx_tasks_deleted_at" ON "tasks" ("deleted_at");
CREATE INDEX "idx_sprints_deleted_at" ON "sprints" ("deleted_at");

-- Recycle Bin "Restore All" -- groups items soft-deleted together by
-- the same cascade operation (see workItemDeletionService.js)
CREATE INDEX "idx_epics_deleted_batch" ON "epics" ("deleted_batch_id");
CREATE INDEX "idx_features_deleted_batch" ON "features" ("deleted_batch_id");
CREATE INDEX "idx_user_stories_deleted_batch" ON "user_stories" ("deleted_batch_id");
CREATE INDEX "idx_tasks_deleted_batch" ON "tasks" ("deleted_batch_id");
CREATE INDEX "fk_users_mentor" ON "users" ("mentor_id");
CREATE INDEX "fk_users_reporting_manager" ON "users" ("reporting_manager_id");
CREATE INDEX "idx_users_department_status" ON "users" ("department_id","employment_status");
CREATE INDEX "fk_users_organization" ON "users" ("organization_id");
CREATE INDEX "fk_wil_project" ON "work_item_links" ("project_id");
CREATE INDEX "fk_wil_created_by" ON "work_item_links" ("created_by");
CREATE INDEX "idx_wil_target" ON "work_item_links" ("target_type","target_id");
