-- ==========================================
-- GROWORGS CANONICAL TENANT SCHEMA (Phase 2C)
-- Generated 2026-09-03T10:54:20.156Z via SHOW CREATE TABLE
-- against the live tenant database "reinsteins_workhub".
-- Source table count: 37
--
-- This file contains STRUCTURE ONLY -- no rows, no business
-- data. It is applied verbatim to a freshly created, empty
-- tenant database by tenantProvisioningService.js.
--
-- Regenerate with: node _generate_tenant_schema.js
-- ==========================================

SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `attendance` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `user_id` integer NOT NULL,
  `login_time` datetime(6) NOT NULL,
  `logout_time` datetime(6) DEFAULT NULL,
  `work_duration_seconds` bigint DEFAULT NULL,
  `status` enum('working','break','completed') NOT NULL DEFAULT 'working',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `break_start_time` datetime(6) DEFAULT NULL,
  `total_break_seconds` int NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`id`),
  KEY `idx_attendance_user_id` (`user_id`),
  KEY `idx_attendance_login_time` (`login_time`),
  KEY `idx_attendance_status` (`status`),
  CONSTRAINT `fk_attendance_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);

CREATE TABLE `chat_attachments` (
  `id` biginteger GENERATED BY DEFAULT AS IDENTITY,
  `message_id` bigint NOT NULL,
  `original_name` varchar(255) NOT NULL,
  `stored_name` varchar(255) NOT NULL,
  `file_type` varchar(100) NOT NULL,
  `file_size` bigint NOT NULL,
  `file_path` varchar(500) NOT NULL,
  `uploaded_by` integer NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_attachment_message` (`message_id`),
  KEY `fk_attachment_user` (`uploaded_by`),
  CONSTRAINT `fk_attachment_message` FOREIGN KEY (`message_id`) REFERENCES `messages` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_attachment_user` FOREIGN KEY (`uploaded_by`) REFERENCES `users` (`id`) ON DELETE CASCADE
);

CREATE TABLE `conversation_members` (
  `id` biginteger GENERATED BY DEFAULT AS IDENTITY,
  `conversation_id` bigint NOT NULL,
  `user_id` integer NOT NULL,
  `joined_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_read_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_conversation_member` (`conversation_id`,`user_id`),
  KEY `idx_conversation_members_user` (`user_id`),
  CONSTRAINT `fk_conversation_members_conversation` FOREIGN KEY (`conversation_id`) REFERENCES `conversations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_conversation_members_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);

CREATE TABLE `conversations` (
  `id` biginteger GENERATED BY DEFAULT AS IDENTITY,
  `conversation_type` enum('private','group') NOT NULL DEFAULT 'private',
  `name` varchar(150) DEFAULT NULL,
  `created_by` integer NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_conversations_updated_at` (`updated_at`),
  KEY `fk_conversations_created_by` (`created_by`),
  CONSTRAINT `fk_conversations_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE
);

CREATE TABLE `departments` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `name` varchar(150) NOT NULL,
  `code` varchar(20) NOT NULL,
  `description` text,
  `department_head_id` integer DEFAULT NULL,
  `status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `organization_id` integer DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_departments_code` (`code`),
  KEY `fk_departments_head` (`department_head_id`),
  KEY `fk_departments_organization` (`organization_id`),
  CONSTRAINT `fk_departments_head` FOREIGN KEY (`department_head_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_departments_organization` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE SET NULL
);

CREATE TABLE `designations` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `title` varchar(100) NOT NULL,
  `department_id` integer DEFAULT NULL,
  `status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `organization_id` integer DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_designations_title` (`title`),
  KEY `fk_designations_department` (`department_id`),
  KEY `fk_designations_organization` (`organization_id`),
  CONSTRAINT `fk_designations_department` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_designations_organization` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE SET NULL
);

CREATE TABLE `employment_history` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `user_id` integer NOT NULL,
  `employment_type` enum('employee','intern') NOT NULL DEFAULT 'employee',
  `identifier` varchar(30) DEFAULT NULL,
  `designation` varchar(100) DEFAULT NULL,
  `start_date` date NOT NULL,
  `end_date` date DEFAULT NULL,
  `employment_status` enum('active','inactive','resigned','terminated','retired','completed','discontinued','converted') NOT NULL DEFAULT 'active',
  `notes` text,
  `exit_reason` text,
  `exit_notes` text,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_employment_history_user` (`user_id`),
  CONSTRAINT `fk_employment_history_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);

CREATE TABLE `epics` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `project_id` integer NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text,
  `owner_id` integer DEFAULT NULL,
  `created_by` integer NOT NULL,
  `priority` enum('Low','Medium','High','Critical') NOT NULL DEFAULT 'Medium',
  `status` enum('new','active','on_hold','completed','cancelled') NOT NULL DEFAULT 'new',
  `start_date` date DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_epics_project` (`project_id`),
  KEY `fk_epics_owner` (`owner_id`),
  KEY `fk_epics_created_by` (`created_by`),
  CONSTRAINT `fk_epics_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_epics_owner` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_epics_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE
);

CREATE TABLE `features` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `project_id` integer NOT NULL,
  `epic_id` integer DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `description` text,
  `owner_id` integer DEFAULT NULL,
  `created_by` integer NOT NULL,
  `priority` enum('Low','Medium','High','Critical') NOT NULL DEFAULT 'Medium',
  `status` enum('new','active','on_hold','completed','cancelled') NOT NULL DEFAULT 'new',
  `start_date` date DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_features_project` (`project_id`),
  KEY `fk_features_epic` (`epic_id`),
  KEY `fk_features_owner` (`owner_id`),
  KEY `fk_features_created_by` (`created_by`),
  CONSTRAINT `fk_features_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_features_epic` FOREIGN KEY (`epic_id`) REFERENCES `epics` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_features_owner` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_features_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE
);

CREATE TABLE `leave_requests` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `user_id` integer NOT NULL,
  `manager_id` integer DEFAULT NULL,
  `leave_type` enum('casual','sick','earned','unpaid','other') NOT NULL,
  `from_date` date NOT NULL,
  `to_date` date NOT NULL,
  `reason` text NOT NULL,
  `status` enum('pending_manager','pending_final','manager_rejected','approved','rejected','cancelled') NOT NULL DEFAULT 'pending_final',
  `manager_decision` enum('approved','rejected') DEFAULT NULL,
  `manager_comment` text,
  `manager_decided_at` timestamp NULL DEFAULT NULL,
  `admin_comment` text,
  `final_decided_by` integer DEFAULT NULL,
  `final_decided_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_leave_user` (`user_id`),
  KEY `fk_leave_final_decided_by` (`final_decided_by`),
  KEY `idx_leave_manager_status` (`manager_id`,`status`),
  CONSTRAINT `fk_leave_final_decided_by` FOREIGN KEY (`final_decided_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_leave_manager` FOREIGN KEY (`manager_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_leave_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);

CREATE TABLE `meeting_message_attachments` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `message_id` integer NOT NULL,
  `original_name` varchar(255) NOT NULL,
  `stored_name` varchar(255) NOT NULL,
  `file_type` varchar(150) NOT NULL,
  `file_size` int NOT NULL,
  `file_path` varchar(500) NOT NULL,
  `uploaded_by` integer NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_meeting_msg_attachment_message` (`message_id`),
  KEY `fk_meeting_msg_attachment_uploader` (`uploaded_by`),
  CONSTRAINT `fk_meeting_msg_attachment_message` FOREIGN KEY (`message_id`) REFERENCES `meeting_messages` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_meeting_msg_attachment_uploader` FOREIGN KEY (`uploaded_by`) REFERENCES `users` (`id`)
);

CREATE TABLE `meeting_messages` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `meeting_id` integer NOT NULL,
  `sender_id` integer NOT NULL,
  `message_text` text NOT NULL,
  `message_type` enum('text','image','file') NOT NULL DEFAULT 'text',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_meeting_messages_meeting` (`meeting_id`),
  KEY `fk_meeting_messages_sender` (`sender_id`),
  CONSTRAINT `fk_meeting_messages_meeting` FOREIGN KEY (`meeting_id`) REFERENCES `meetings` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_meeting_messages_sender` FOREIGN KEY (`sender_id`) REFERENCES `users` (`id`)
);

CREATE TABLE `meeting_participants` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `meeting_id` integer NOT NULL,
  `user_id` integer NOT NULL,
  `role` enum('host','co_host','presenter','participant') NOT NULL DEFAULT 'participant',
  `status` enum('waiting','admitted','joined','left','removed','rejected') NOT NULL DEFAULT 'waiting',
  `invited_by` integer DEFAULT NULL,
  `joined_at` datetime DEFAULT NULL,
  `left_at` datetime DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_meeting_participant` (`meeting_id`,`user_id`),
  KEY `fk_meeting_participants_user` (`user_id`),
  KEY `fk_meeting_participants_invited_by` (`invited_by`),
  CONSTRAINT `fk_meeting_participants_invited_by` FOREIGN KEY (`invited_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_meeting_participants_meeting` FOREIGN KEY (`meeting_id`) REFERENCES `meetings` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_meeting_participants_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
);

CREATE TABLE `meetings` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `meeting_code` varchar(20) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text,
  `host_id` integer NOT NULL,
  `meeting_type` enum('instant','scheduled') NOT NULL DEFAULT 'scheduled',
  `scheduled_date` date DEFAULT NULL,
  `start_time` time DEFAULT NULL,
  `end_time` time DEFAULT NULL,
  `password_hash` varchar(255) DEFAULT NULL,
  `allow_guest_join` boolean NOT NULL DEFAULT TRUE,
  `waiting_room_enabled` boolean NOT NULL DEFAULT FALSE,
  `require_host_approval` boolean NOT NULL DEFAULT FALSE,
  `settings` json DEFAULT NULL,
  `status` enum('scheduled','live','ended','cancelled') NOT NULL DEFAULT 'scheduled',
  `is_locked` boolean NOT NULL DEFAULT FALSE,
  `actual_start_time` datetime DEFAULT NULL,
  `actual_end_time` datetime DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_meetings_code` (`meeting_code`),
  KEY `fk_meetings_host` (`host_id`),
  CONSTRAINT `fk_meetings_host` FOREIGN KEY (`host_id`) REFERENCES `users` (`id`)
);

CREATE TABLE `messages` (
  `id` biginteger GENERATED BY DEFAULT AS IDENTITY,
  `conversation_id` bigint NOT NULL,
  `sender_id` integer NOT NULL,
  `message_text` text NOT NULL,
  `message_type` enum('text','image','file') NOT NULL DEFAULT 'text',
  `is_deleted` boolean NOT NULL DEFAULT FALSE,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_messages_conversation_created` (`conversation_id`,`created_at`),
  KEY `idx_messages_sender` (`sender_id`),
  CONSTRAINT `fk_messages_conversation` FOREIGN KEY (`conversation_id`) REFERENCES `conversations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_messages_sender` FOREIGN KEY (`sender_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);

CREATE TABLE `notifications` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `user_id` integer NOT NULL,
  `title` varchar(255) NOT NULL,
  `message` text NOT NULL,
  `type` varchar(50) DEFAULT 'general',
  `reference_type` varchar(30) DEFAULT NULL,
  `reference_id` integer DEFAULT NULL,
  `is_read` boolean DEFAULT FALSE,
  `email_sent_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_notifications_user_id` (`user_id`),
  KEY `idx_notifications_is_read` (`is_read`),
  KEY `idx_notifications_reference` (`reference_type`,`reference_id`),
  CONSTRAINT `fk_notifications_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);

CREATE TABLE `organization_history` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `user_id` integer NOT NULL,
  `change_type` enum('department','designation','reporting_manager','system_access','department_head') NOT NULL,
  `old_value` varchar(255) DEFAULT NULL,
  `new_value` varchar(255) DEFAULT NULL,
  `changed_by` integer NOT NULL,
  `changed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_org_history_user` (`user_id`),
  KEY `idx_org_history_changed_at` (`changed_at`),
  KEY `fk_org_history_changed_by` (`changed_by`),
  CONSTRAINT `fk_org_history_changed_by` FOREIGN KEY (`changed_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_org_history_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);

CREATE TABLE `organization_members` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `organization_id` integer NOT NULL,
  `user_id` integer NOT NULL,
  `added_by` integer DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_om_user` (`user_id`),
  KEY `fk_om_organization` (`organization_id`),
  KEY `fk_om_added_by` (`added_by`),
  CONSTRAINT `fk_om_added_by` FOREIGN KEY (`added_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_om_organization` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_om_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);

CREATE TABLE `organizations` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `name` varchar(255) NOT NULL,
  `description` text,
  `status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `created_by` integer DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_organizations_created_by` (`created_by`),
  CONSTRAINT `fk_organizations_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
);

CREATE TABLE `project_activity` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `project_id` integer NOT NULL,
  `actor_id` integer NOT NULL,
  `activity_type` enum('member_added','member_removed','member_group_changed','permission_changed') NOT NULL,
  `target_user_id` integer DEFAULT NULL,
  `details` text,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_project_activity_project` (`project_id`,`created_at`),
  KEY `fk_pa_actor` (`actor_id`),
  KEY `fk_pa_target` (`target_user_id`),
  CONSTRAINT `fk_pa_actor` FOREIGN KEY (`actor_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_pa_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_pa_target` FOREIGN KEY (`target_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
);

CREATE TABLE `project_members` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `project_id` integer NOT NULL,
  `user_id` integer NOT NULL,
  `security_group_id` integer NOT NULL,
  `added_by` integer NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_project_member` (`project_id`,`user_id`),
  KEY `idx_project_members_user` (`user_id`),
  KEY `fk_pm_group` (`security_group_id`),
  KEY `fk_pm_added_by` (`added_by`),
  CONSTRAINT `fk_pm_added_by` FOREIGN KEY (`added_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_pm_group` FOREIGN KEY (`security_group_id`) REFERENCES `project_security_groups` (`id`),
  CONSTRAINT `fk_pm_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_pm_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);

CREATE TABLE `project_permissions` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `security_group_id` integer NOT NULL,
  `project_id` integer DEFAULT NULL,
  `permission_key` varchar(64) NOT NULL,
  `value` enum('allow','deny','not_set') NOT NULL DEFAULT 'not_set',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_pp_group` (`security_group_id`),
  KEY `fk_pp_project` (`project_id`),
  CONSTRAINT `fk_pp_group` FOREIGN KEY (`security_group_id`) REFERENCES `project_security_groups` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_pp_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE
);

CREATE TABLE `project_security_groups` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `project_id` integer DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `is_default` boolean NOT NULL DEFAULT FALSE,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_psg_project` (`project_id`),
  CONSTRAINT `fk_psg_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE
);

CREATE TABLE `projects` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `name` varchar(255) NOT NULL,
  `description` text,
  `owner_id` integer DEFAULT NULL,
  `created_by` integer NOT NULL,
  `status` enum('planning','active','on_hold','completed','cancelled') NOT NULL DEFAULT 'planning',
  `priority` enum('Low','Medium','High','Critical') NOT NULL DEFAULT 'Medium',
  `start_date` date DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `organization_id` integer DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_projects_owner` (`owner_id`),
  KEY `fk_projects_created_by` (`created_by`),
  KEY `fk_projects_organization` (`organization_id`),
  CONSTRAINT `fk_projects_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_projects_organization` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_projects_owner` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`)
);

CREATE TABLE `sprints` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `project_id` integer NOT NULL,
  `name` varchar(100) NOT NULL,
  `goal` text,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `status` enum('planning','active','completed') NOT NULL DEFAULT 'planning',
  `created_by` integer NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active_marker` integer GENERATED ALWAYS AS (CASE WHEN `status` = 'active' THEN 1 ELSE NULL END) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sprint_name_per_project` (`project_id`,`name`),
  UNIQUE KEY `uq_one_active_sprint_per_project` (`project_id`,`active_marker`),
  KEY `fk_sprints_project` (`project_id`),
  KEY `fk_sprints_created_by` (`created_by`),
  CONSTRAINT `fk_sprints_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_sprints_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `chk_sprint_dates` CHECK (((`end_date` is null) or (`start_date` is null) or (`end_date` >= `start_date`)))
);

CREATE TABLE `tags` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `name` varchar(50) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_tag_name` (`name`)
);

CREATE TABLE `task_activity` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `task_id` integer NOT NULL,
  `author_id` integer NOT NULL,
  `activity_type` enum('comment','work_update','status_change','system') NOT NULL DEFAULT 'comment',
  `body` text,
  `progress_snapshot` int DEFAULT NULL,
  `old_status` varchar(30) DEFAULT NULL,
  `new_status` varchar(30) DEFAULT NULL,
  `is_edited` boolean NOT NULL DEFAULT FALSE,
  `is_deleted` boolean NOT NULL DEFAULT FALSE,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_task_activity_task` (`task_id`),
  KEY `fk_task_activity_author` (`author_id`),
  CONSTRAINT `fk_task_activity_author` FOREIGN KEY (`author_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_task_activity_task` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`) ON DELETE CASCADE
);

CREATE TABLE `task_assignments` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `task_id` integer NOT NULL,
  `assigned_by` integer NOT NULL,
  `assigned_to` integer NOT NULL,
  `remarks` text,
  `assigned_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_task_assignment_task` (`task_id`),
  KEY `fk_task_assignment_assigned_by` (`assigned_by`),
  KEY `fk_task_assignment_assigned_to` (`assigned_to`),
  CONSTRAINT `fk_task_assignment_assigned_by` FOREIGN KEY (`assigned_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_task_assignment_assigned_to` FOREIGN KEY (`assigned_to`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_task_assignment_task` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`) ON DELETE CASCADE
);

CREATE TABLE `task_attachments` (
  `id` biginteger GENERATED BY DEFAULT AS IDENTITY,
  `activity_id` integer NOT NULL,
  `original_name` varchar(255) NOT NULL,
  `stored_name` varchar(255) NOT NULL,
  `file_type` varchar(100) NOT NULL,
  `file_size` bigint NOT NULL,
  `file_path` varchar(500) NOT NULL,
  `uploaded_by` integer NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_task_attachment_activity` (`activity_id`),
  KEY `fk_task_attachment_user` (`uploaded_by`),
  CONSTRAINT `fk_task_attachment_activity` FOREIGN KEY (`activity_id`) REFERENCES `task_activity` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_task_attachment_user` FOREIGN KEY (`uploaded_by`) REFERENCES `users` (`id`)
);

CREATE TABLE `task_mentions` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `activity_id` integer NOT NULL,
  `mentioned_user_id` integer NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_task_mention_activity` (`activity_id`),
  KEY `fk_task_mention_user` (`mentioned_user_id`),
  CONSTRAINT `fk_task_mention_activity` FOREIGN KEY (`activity_id`) REFERENCES `task_activity` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_task_mention_user` FOREIGN KEY (`mentioned_user_id`) REFERENCES `users` (`id`)
);

CREATE TABLE `task_tags` (
  `task_id` integer NOT NULL,
  `tag_id` integer NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`task_id`,`tag_id`),
  KEY `idx_task_tags_tag_id` (`tag_id`),
  CONSTRAINT `fk_task_tags_tag` FOREIGN KEY (`tag_id`) REFERENCES `tags` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_task_tags_task` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`) ON DELETE CASCADE
);

CREATE TABLE `task_transfer_requests` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `task_id` integer NOT NULL,
  `requested_by` integer NOT NULL,
  `current_assignee_id` integer NOT NULL,
  `proposed_assignee_id` integer NOT NULL,
  `reason` text,
  `approver_id` integer DEFAULT NULL,
  `status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `decided_by` integer DEFAULT NULL,
  `decided_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_transfer_task` (`task_id`),
  KEY `idx_transfer_approver` (`approver_id`,`status`),
  KEY `fk_transfer_requested_by` (`requested_by`),
  KEY `fk_transfer_current_assignee` (`current_assignee_id`),
  KEY `fk_transfer_proposed_assignee` (`proposed_assignee_id`),
  KEY `fk_transfer_decided_by` (`decided_by`),
  CONSTRAINT `fk_transfer_approver` FOREIGN KEY (`approver_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_transfer_current_assignee` FOREIGN KEY (`current_assignee_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_transfer_decided_by` FOREIGN KEY (`decided_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_transfer_proposed_assignee` FOREIGN KEY (`proposed_assignee_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_transfer_requested_by` FOREIGN KEY (`requested_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_transfer_task` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`) ON DELETE CASCADE
);

CREATE TABLE `task_work_logs` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `task_id` integer NOT NULL,
  `employee_id` integer NOT NULL,
  `work_description` text NOT NULL,
  `hours_worked` decimal(5,2) NOT NULL,
  `progress` int NOT NULL,
  `status` enum('New','Assigned','In Progress','On Hold','Review','Completed','Closed') NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_worklog_task` (`task_id`),
  KEY `fk_worklog_employee` (`employee_id`),
  CONSTRAINT `fk_worklog_employee` FOREIGN KEY (`employee_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_worklog_task` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`) ON DELETE CASCADE
);

CREATE TABLE `tasks` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `task_number` varchar(20) DEFAULT NULL,
  `user_id` integer NOT NULL,
  `project_id` integer DEFAULT NULL,
  `user_story_id` integer DEFAULT NULL,
  `sprint_id` integer DEFAULT NULL,
  `assigned_to` integer DEFAULT NULL,
  `assigned_by` integer DEFAULT NULL,
  `task_title` varchar(255) NOT NULL,
  `task_description` text NOT NULL,
  `priority` enum('Low','Medium','High','Critical') DEFAULT 'Medium',
  `start_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `completed_time` datetime(6) DEFAULT NULL,
  `admin_closed_time` datetime DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `status` enum('backlog','todo','in_progress','pending_review','closed') NOT NULL DEFAULT 'in_progress',
  `due_date` date DEFAULT NULL,
  `progress` int DEFAULT FALSE,
  `estimated_hours` decimal(5,2) DEFAULT NULL,
  `actual_hours` decimal(5,2) DEFAULT NULL,
  `tags` varchar(255) DEFAULT NULL,
  `work_started_at` datetime DEFAULT NULL,
  `current_working` boolean DEFAULT FALSE,
  `admin_closed` boolean NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`id`),
  KEY `fk_tasks_user` (`user_id`),
  KEY `fk_tasks_project` (`project_id`),
  KEY `fk_tasks_user_story` (`user_story_id`),
  KEY `fk_tasks_sprint` (`sprint_id`),
  CONSTRAINT `fk_tasks_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_tasks_sprint` FOREIGN KEY (`sprint_id`) REFERENCES `sprints` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_tasks_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_tasks_user_story` FOREIGN KEY (`user_story_id`) REFERENCES `user_stories` (`id`) ON DELETE SET NULL
);

CREATE TABLE `user_stories` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `project_id` integer NOT NULL,
  `feature_id` integer DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `description` text,
  `owner_id` integer DEFAULT NULL,
  `created_by` integer NOT NULL,
  `priority` enum('Low','Medium','High','Critical') NOT NULL DEFAULT 'Medium',
  `status` enum('new','active','on_hold','completed','cancelled') NOT NULL DEFAULT 'new',
  `start_date` date DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `tags` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_user_stories_project` (`project_id`),
  KEY `fk_user_stories_owner` (`owner_id`),
  KEY `fk_user_stories_created_by` (`created_by`),
  KEY `fk_user_stories_feature` (`feature_id`),
  CONSTRAINT `fk_user_stories_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_user_stories_feature` FOREIGN KEY (`feature_id`) REFERENCES `features` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_user_stories_owner` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_user_stories_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE
);

CREATE TABLE `users` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `employee_id` varchar(30) NOT NULL,
  `first_name` varchar(50) DEFAULT NULL,
  `last_name` varchar(50) DEFAULT NULL,
  `full_name` varchar(100) NOT NULL,
  `email` varchar(150) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `address` text,
  `date_of_birth` date DEFAULT NULL,
  `designation` varchar(100) DEFAULT NULL,
  `department_id` integer DEFAULT NULL,
  `employment_status` enum('active','inactive','resigned','terminated','retired','completed','discontinued','converted') NOT NULL DEFAULT 'active',
  `joining_date` date DEFAULT NULL,
  `last_working_date` date DEFAULT NULL,
  `internship_end_date` date DEFAULT NULL,
  `mentor_id` integer DEFAULT NULL,
  `reporting_manager_id` integer DEFAULT NULL,
  `stipend` decimal(10,2) DEFAULT NULL,
  `exited_at` timestamp NULL DEFAULT NULL,
  `exit_reason` text,
  `exit_notes` text,
  `emergency_contact` varchar(20) DEFAULT NULL,
  `profile_photo` varchar(255) DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `role` enum('admin','employee') NOT NULL DEFAULT 'employee',
  `system_access` enum('super_admin','admin','executive','hr','department_head','manager','team_lead','employee') NOT NULL DEFAULT 'employee',
  `project_access_override` enum('granted','revoked') DEFAULT NULL,
  `project_access_level` enum('stakeholder','basic') NOT NULL DEFAULT 'basic',
  `employment_type` enum('employee','intern') NOT NULL DEFAULT 'employee',
  `status` enum('pending','active','inactive') NOT NULL DEFAULT 'pending',
  `last_login` datetime DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `organization_id` integer DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `employee_id` (`employee_id`),
  UNIQUE KEY `email` (`email`),
  KEY `fk_users_mentor` (`mentor_id`),
  KEY `fk_users_reporting_manager` (`reporting_manager_id`),
  KEY `idx_users_department_status` (`department_id`,`employment_status`),
  KEY `fk_users_organization` (`organization_id`),
  CONSTRAINT `fk_users_department` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_users_mentor` FOREIGN KEY (`mentor_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_users_organization` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_users_reporting_manager` FOREIGN KEY (`reporting_manager_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
);

CREATE TABLE `work_item_links` (
  `id` integer GENERATED BY DEFAULT AS IDENTITY,
  `source_type` enum('epic','feature','user_story','task') NOT NULL,
  `source_id` integer NOT NULL,
  `target_type` enum('epic','feature','user_story','task') NOT NULL,
  `target_id` integer NOT NULL,
  `link_type` enum('related','blocks') NOT NULL,
  `project_id` integer NOT NULL,
  `created_by` integer NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_work_item_link` (`source_type`,`source_id`,`target_type`,`target_id`,`link_type`),
  KEY `fk_wil_project` (`project_id`),
  KEY `fk_wil_created_by` (`created_by`),
  KEY `idx_wil_target` (`target_type`,`target_id`),
  CONSTRAINT `fk_wil_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_wil_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE
);
SET FOREIGN_KEY_CHECKS=1;
