import { useState } from "react";

import platformApi from "../../services/platformApi";

// ==========================================
// ADD COMPANY MODAL (Phase 4)
//
// Collects only companyName / companySlug / accessType -- exactly
// what POST /api/platform/companies accepts. tenant_db_name, company
// id, and status are never fields on this form; they are entirely
// server-controlled (buildTenantDbName + the provisioning saga in
// platformCompanyController.js), matching Part 4's requirement.
// ==========================================

const ACCESS_TYPES = [
  { value: "complimentary", label: "Complimentary" },
  { value: "trial", label: "Trial" },
  { value: "paid", label: "Paid" },
];

function AddCompanyModal({ onClose, onCreated }) {
  const [companyName, setCompanyName] = useState("");
  const [companySlug, setCompanySlug] = useState("");
  const [accessType, setAccessType] = useState("trial");
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState(null);
  const [step, setStep] = useState("form"); // "form" | "provisioning"

  const handleSubmit = async (event) => {
    event.preventDefault();
    setError(null);

    if (!companyName.trim() || !companySlug.trim()) {
      setError("Company name and slug are required.");
      return;
    }

    try {
      setSubmitting(true);
      setStep("provisioning");

      // This single request creates the platform company row AND
      // provisions its tenant database (existing saga in
      // tenantProvisioningService.js / platformCompanyController.js)
      // -- the company is only marked active after provisioning
      // succeeds, so there is nothing further for this UI to
      // orchestrate.
      const response = await platformApi.post("/companies", {
        companyName: companyName.trim(),
        companySlug: companySlug.trim().toLowerCase(),
        accessType,
      });

      onCreated(response.data.company);

    } catch (err) {
      setStep("form");
      setError(err.response?.data?.message || "Failed to create company.");
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="platform-modal-backdrop" onClick={onClose}>
      <div className="platform-modal" onClick={(event) => event.stopPropagation()}>

        <div className="platform-modal-header">
          <div>
            <h2>Add Company</h2>
            <p>Creates the company and provisions its tenant database.</p>
          </div>
          <button className="platform-modal-close" onClick={onClose} aria-label="Close">×</button>
        </div>

        <div className="platform-modal-body">

          {error && <div className="platform-alert platform-alert-danger">{error}</div>}

          {step === "provisioning" ? (
            <div className="platform-empty-state">Creating company and provisioning its tenant database…</div>
          ) : (
            <form onSubmit={handleSubmit}>

              <div className="platform-form-group">
                <label htmlFor="company-name">Company Name</label>
                <input
                  id="company-name"
                  type="text"
                  placeholder="Arckenets Technologies"
                  value={companyName}
                  onChange={(event) => setCompanyName(event.target.value)}
                />
              </div>

              <div className="platform-form-group">
                <label htmlFor="company-slug">Company Slug</label>
                <input
                  id="company-slug"
                  type="text"
                  placeholder="arckenets"
                  value={companySlug}
                  onChange={(event) => setCompanySlug(event.target.value)}
                />
                <p className="platform-form-hint">
                  Lowercase, letters/digits/underscore only. Determines the tenant login URL and database name — the actual database name is generated by the server, never chosen here.
                </p>
              </div>

              <div className="platform-form-group">
                <label htmlFor="access-type">Access Type</label>
                <select
                  id="access-type"
                  value={accessType}
                  onChange={(event) => setAccessType(event.target.value)}
                >
                  {ACCESS_TYPES.map((option) => (
                    <option key={option.value} value={option.value}>{option.label}</option>
                  ))}
                </select>
              </div>

            </form>
          )}

        </div>

        {step === "form" && (
          <div className="platform-modal-footer">
            <button className="platform-btn platform-btn-outline" onClick={onClose} disabled={submitting}>
              Cancel
            </button>
            <button className="platform-btn platform-btn-primary" onClick={handleSubmit} disabled={submitting}>
              {submitting ? "Creating..." : "Create Company"}
            </button>
          </div>
        )}

      </div>
    </div>
  );
}

export default AddCompanyModal;
