// Explicit, cwd-independent path -- same fix as
// _migrate_backfill_admin_group_permissions.js/_migrate_backfill_system_administrator.js
// (see their header comments for why this is needed for an
// unattended deploy-pipeline run): dotenv's no-argument default
// resolves ".env" relative to process.cwd(), which is only "server/"
// when something has `cd`'d into this directory first -- this script
// is invoked as `node server/_migrate_....js` from the repo root.
require("dotenv").config({ path: require("path").join(__dirname, ".env") });

const platformPool = require("./config/platformDb");
const { getTenantPool, closeAllTenantPools } = require("./config/tenantConnectionManager");

// ==========================================
// ADD SHIFT SCHEDULE TABLES TO EXISTING TENANTS (Phase 17b)
//
// server/schemas/tenantSchema.postgresql.sql now includes
// "shift_schedules"/"shift_schedule_history" so every NEWLY
// provisioned tenant gets them automatically (tenantProvisioningService.js
// applies that file verbatim to a fresh, empty database). This script
// is the one-off companion for tenants that were already provisioned
// before this phase -- there is no existing "run this against every
// tenant DB" mechanism in this codebase (confirmed: no
// server/migrations/ folder, no tenant-side equivalent of
// _setup_platform_db.js), so this establishes that pattern narrowly
// for this one feature rather than building a general migration
// runner that isn't otherwise needed yet.
//
// Idempotent and safe to run more than once: every statement either
// checks information_schema first or uses IF NOT EXISTS. Never drops,
// truncates, or modifies any existing table/row.
// ==========================================

async function tableExists(tenantPool, tableName) {
    const [rows] = await tenantPool.query(
        `SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = ? LIMIT 1`,
        [tableName]
    );
    return rows.length > 0;
}

async function migrateTenant(companySlug, tenantDbName) {
    const tenantPool = getTenantPool(tenantDbName);

    const alreadyDone = await tableExists(tenantPool, "shift_schedules");

    if (alreadyDone) {
        console.log(`  [skip] ${companySlug} (${tenantDbName}) -- shift_schedules already exists`);
        return;
    }

    console.log(`  [migrate] ${companySlug} (${tenantDbName}) -- creating shift schedule tables...`);

    // Table creation order matters here (shift_schedule_history's FK
    // references shift_schedules), the ADD CONSTRAINT/CREATE INDEX
    // statements below do not depend on order.

    await tenantPool.query(`
        CREATE TABLE "shift_schedules" (
          "id" integer GENERATED BY DEFAULT AS IDENTITY,
          "user_id" integer NOT NULL,
          "shift_date" date NOT NULL,
          "status" varchar NOT NULL DEFAULT 'working' CHECK ("status" IN ('working', 'off', 'leave')),
          "start_time" time DEFAULT NULL,
          "end_time" time DEFAULT NULL,
          "notes" text,
          "created_by" integer DEFAULT NULL,
          "updated_by" integer DEFAULT NULL,
          "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
          "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
          PRIMARY KEY ("id")
        )
    `);

    await tenantPool.query(`
        CREATE TABLE "shift_schedule_history" (
          "id" integer GENERATED BY DEFAULT AS IDENTITY,
          "shift_schedule_id" integer DEFAULT NULL,
          "user_id" integer DEFAULT NULL,
          "action" varchar NOT NULL CHECK ("action" IN ('created', 'updated', 'deleted')),
          "old_value" json DEFAULT NULL,
          "new_value" json DEFAULT NULL,
          "changed_by" integer DEFAULT NULL,
          "changed_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
          PRIMARY KEY ("id")
        )
    `);

    await tenantPool.query(`ALTER TABLE "shift_schedules" ADD CONSTRAINT "fk_shift_schedules_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE`);
    await tenantPool.query(`ALTER TABLE "shift_schedules" ADD CONSTRAINT "fk_shift_schedules_created_by" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON DELETE SET NULL`);
    await tenantPool.query(`ALTER TABLE "shift_schedules" ADD CONSTRAINT "fk_shift_schedules_updated_by" FOREIGN KEY ("updated_by") REFERENCES "users" ("id") ON DELETE SET NULL`);
    await tenantPool.query(`ALTER TABLE "shift_schedule_history" ADD CONSTRAINT "fk_ssh_shift" FOREIGN KEY ("shift_schedule_id") REFERENCES "shift_schedules" ("id") ON DELETE SET NULL`);
    await tenantPool.query(`ALTER TABLE "shift_schedule_history" ADD CONSTRAINT "fk_ssh_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL`);
    await tenantPool.query(`ALTER TABLE "shift_schedule_history" ADD CONSTRAINT "fk_ssh_changed_by" FOREIGN KEY ("changed_by") REFERENCES "users" ("id") ON DELETE SET NULL`);

    await tenantPool.query(`CREATE INDEX IF NOT EXISTS "idx_shift_schedules_user_id" ON "shift_schedules" ("user_id")`);
    await tenantPool.query(`CREATE INDEX IF NOT EXISTS "idx_shift_schedules_shift_date" ON "shift_schedules" ("shift_date")`);
    await tenantPool.query(`CREATE INDEX IF NOT EXISTS "idx_shift_schedules_user_date" ON "shift_schedules" ("user_id", "shift_date")`);
    await tenantPool.query(`CREATE INDEX IF NOT EXISTS "idx_shift_schedule_history_shift" ON "shift_schedule_history" ("shift_schedule_id")`);
    await tenantPool.query(`CREATE INDEX IF NOT EXISTS "idx_shift_schedule_history_user" ON "shift_schedule_history" ("user_id")`);

    console.log(`  [done] ${companySlug} (${tenantDbName})`);
}

(async () => {
    console.log("Shift schedule migration -- enumerating provisioned tenant databases...\n");

    const [companies] = await platformPool.query(
        `SELECT company_slug, tenant_db_name FROM companies WHERE tenant_db_name IS NOT NULL AND tenant_db_name <> ''`
    );

    if (companies.length === 0) {
        console.log("No provisioned tenant databases found.");
    }

    let failures = 0;

    for (const company of companies) {
        try {
            await migrateTenant(company.company_slug, company.tenant_db_name);
        } catch (error) {
            failures++;
            console.error(`  [FAILED] ${company.company_slug} (${company.tenant_db_name}):`, error.message);
        }
    }

    await closeAllTenantPools();
    await platformPool.end();

    console.log(`\n${failures === 0 ? "All tenants migrated successfully." : `${failures} tenant(s) failed -- see errors above.`}`);
    process.exit(failures === 0 ? 0 : 1);
})().catch(async (error) => {
    console.error("MIGRATION SCRIPT ERROR:", error);
    process.exit(1);
});
