require("dotenv").config();

const platformPool = require("./config/platformDb");
const { getTenantPool, closeAllTenantPools } = require("./config/tenantConnectionManager");

// ==========================================
// ADD SOP TABLE TO EXISTING TENANTS (Phase 17c)
//
// server/schemas/tenantSchema.postgresql.sql now includes "sops" so
// every NEWLY provisioned tenant gets it automatically. This is the
// one-off companion for tenants that were already provisioned before
// this phase -- same pattern as _migrate_add_shift_schedules.js.
//
// Idempotent and safe to run more than once: checks
// information_schema before doing anything, and never drops,
// truncates, or modifies any existing table/row.
// ==========================================

async function tableExists(tenantPool, tableName) {
    const [rows] = await tenantPool.query(
        `SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = ? LIMIT 1`,
        [tableName]
    );
    return rows.length > 0;
}

async function migrateTenant(companySlug, tenantDbName) {
    const tenantPool = getTenantPool(tenantDbName);

    const alreadyDone = await tableExists(tenantPool, "sops");

    if (alreadyDone) {
        console.log(`  [skip] ${companySlug} (${tenantDbName}) -- sops already exists`);
        return;
    }

    console.log(`  [migrate] ${companySlug} (${tenantDbName}) -- creating sops table...`);

    await tenantPool.query(`
        CREATE TABLE "sops" (
          "id" integer GENERATED BY DEFAULT AS IDENTITY,
          "title" varchar(255) NOT NULL,
          "original_filename" varchar(255) NOT NULL,
          "stored_filename" varchar(255) NOT NULL,
          "file_path" varchar(500) NOT NULL,
          "file_size" bigint NOT NULL,
          "mime_type" varchar(100) NOT NULL,
          "uploaded_by" integer DEFAULT NULL,
          "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
          "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
          PRIMARY KEY ("id")
        )
    `);

    await tenantPool.query(`ALTER TABLE "sops" ADD CONSTRAINT "fk_sops_uploaded_by" FOREIGN KEY ("uploaded_by") REFERENCES "users" ("id") ON DELETE SET NULL`);
    await tenantPool.query(`CREATE INDEX IF NOT EXISTS "idx_sops_created_at" ON "sops" ("created_at")`);
    await tenantPool.query(`CREATE INDEX IF NOT EXISTS "idx_sops_uploaded_by" ON "sops" ("uploaded_by")`);

    console.log(`  [done] ${companySlug} (${tenantDbName})`);
}

(async () => {
    console.log("SOP migration -- enumerating provisioned tenant databases...\n");

    const [companies] = await platformPool.query(
        `SELECT company_slug, tenant_db_name FROM companies WHERE tenant_db_name IS NOT NULL AND tenant_db_name <> ''`
    );

    if (companies.length === 0) {
        console.log("No provisioned tenant databases found.");
    }

    let failures = 0;

    for (const company of companies) {
        try {
            await migrateTenant(company.company_slug, company.tenant_db_name);
        } catch (error) {
            failures++;
            console.error(`  [FAILED] ${company.company_slug} (${company.tenant_db_name}):`, error.message);
        }
    }

    await closeAllTenantPools();
    await platformPool.end();

    console.log(`\n${failures === 0 ? "All tenants migrated successfully." : `${failures} tenant(s) failed -- see errors above.`}`);
    process.exit(failures === 0 ? 0 : 1);
})().catch(async (error) => {
    console.error("MIGRATION SCRIPT ERROR:", error);
    process.exit(1);
});
