// Explicit, cwd-independent path -- same fix as
// _migrate_backfill_admin_group_permissions.js/_migrate_backfill_system_administrator.js/
// _migrate_add_shift_schedules.js/_migrate_add_company_logo.js (see
// their header comments for why this is needed for an unattended
// deploy-pipeline run).
require("dotenv").config({ path: require("path").join(__dirname, ".env") });

const platformPool = require("./config/platformDb");

// ==========================================
// ADD email_domains / mailboxes / email_aliases / mailbox_settings
// (PLATFORM DB, one-off companion for an already-provisioned platform
// database)
//
// server/schemas/platformSchema.postgresql.sql already includes these
// four tables (added by an earlier commit, "397c8a4 -- fix: complete
// employee email domain feature modules") -- but that commit never
// shipped a corresponding one-off migration for a platform database
// that was already bootstrapped before it landed, and no deploy.yml
// step ever applied it. Same gap-class as _migrate_add_shift_schedules.js,
// just discovered later: platformCompanyController.js's
// getCompanyDetails calls emailDomainService.getEmailSummaryForCompany()
// unconditionally, which queries email_domains/mailboxes directly --
// on a platform database missing these tables, that throws "relation
// ... does not exist" and (before this same change's PART 4 fix)
// aborted the entire Company Details page with a generic 500.
//
// The SQL below is copied VERBATIM from
// schemas/platformSchema.postgresql.sql (the "EMAIL DOMAINS / MAILBOXES
// (Phase 16A)" section: email_domains -> mailboxes -> email_aliases ->
// mailbox_settings, exactly that order because mailboxes.domain_id
// references email_domains, and email_aliases.mailbox_id /
// mailbox_settings.mailbox_id both reference mailboxes) -- not
// reconstructed or simplified, so it can never drift from the
// canonical schema. Applied via the raw driver (platformPool.nativePool),
// PostgreSQL's simple query protocol, the same mechanism
// _setup_platform_db.js already uses to apply this exact file --
// required because the DO $$ ... END $$ constraint guards contain
// their own internal semicolons, which a naive split-on-";" approach
// (as some earlier, simpler _migrate_add_*.js scripts use) would break.
//
// Idempotent: every statement is CREATE TABLE IF NOT EXISTS,
// CREATE INDEX IF NOT EXISTS, or a DO $$ block that checks
// pg_constraint before adding a foreign key -- identical guarantee to
// running the platform schema bootstrap itself, safe to run against a
// database that already has some or all of these tables. Never drops,
// truncates, alters, or reads any existing row's data -- table/index/
// constraint creation only.
// ==========================================

const EMAIL_PLATFORM_TABLES_SQL = `
-- ---------- email_domains ----------
CREATE TABLE IF NOT EXISTS "email_domains" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "company_id" integer NOT NULL,
  "domain" varchar(255) NOT NULL,
  "verification_status" varchar NOT NULL DEFAULT 'pending' CHECK ("verification_status" IN ('pending', 'verified', 'failed')),
  "verification_method" varchar(20) NOT NULL DEFAULT 'dns_txt',
  "verification_token" varchar(64) NOT NULL,
  "verified_at" timestamp DEFAULT NULL,
  "status" varchar NOT NULL DEFAULT 'active' CHECK ("status" IN ('active', 'disabled')),
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_email_domains_domain" UNIQUE ("domain")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_emaildomains_company_id') THEN
    ALTER TABLE "email_domains" ADD CONSTRAINT "fk_emaildomains_company_id" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "idx_emaildomains_company_id" ON "email_domains" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_emaildomains_status" ON "email_domains" ("verification_status");

-- ---------- mailboxes ----------
-- mailbox_provider_id/provisioning_status track the REAL mail-server
-- side of a mailbox once one is connected (Step 5-7) -- NULL /
-- 'pending_infrastructure' until then. This is the honest line
-- between "ZioVenture has a real, authorized record of this
-- mailbox's existence and ownership" (true today) and "a real mail
-- server actually created a working inbox" (not yet -- see the Phase
-- 16A report's "what is NOT implemented" section). Never pretend the
-- second by faking the first.
CREATE TABLE IF NOT EXISTS "mailboxes" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "company_id" integer NOT NULL,
  "domain_id" integer NOT NULL,
  "tenant_user_id" integer NOT NULL,
  "email_address" varchar(255) NOT NULL,
  "mailbox_provider_id" varchar(255) DEFAULT NULL,
  "provisioning_status" varchar NOT NULL DEFAULT 'pending_infrastructure' CHECK ("provisioning_status" IN ('pending_infrastructure', 'provisioned', 'failed')),
  "status" varchar NOT NULL DEFAULT 'active' CHECK ("status" IN ('active', 'suspended', 'disabled')),
  "quota_mb" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_mailboxes_email_address" UNIQUE ("email_address")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_mailboxes_company_id') THEN
    ALTER TABLE "mailboxes" ADD CONSTRAINT "fk_mailboxes_company_id" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_mailboxes_domain_id') THEN
    ALTER TABLE "mailboxes" ADD CONSTRAINT "fk_mailboxes_domain_id" FOREIGN KEY ("domain_id") REFERENCES "email_domains" ("id") ON DELETE CASCADE;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "idx_mailboxes_company_id" ON "mailboxes" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_mailboxes_domain_id" ON "mailboxes" ("domain_id");
CREATE INDEX IF NOT EXISTS "idx_mailboxes_tenant_user_id" ON "mailboxes" ("tenant_user_id");
CREATE INDEX IF NOT EXISTS "idx_mailboxes_status" ON "mailboxes" ("status");

-- ---------- email_aliases ----------
-- Foundation table only in Phase 16A -- schema exists, no CRUD API
-- yet (Step 18: "Do not implement unnecessary endpoints yet"; the
-- 16 required test scenarios cover domains + mailboxes only).
CREATE TABLE IF NOT EXISTS "email_aliases" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "company_id" integer NOT NULL,
  "mailbox_id" integer NOT NULL,
  "alias_address" varchar(255) NOT NULL,
  "status" varchar NOT NULL DEFAULT 'active' CHECK ("status" IN ('active', 'disabled')),
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_email_aliases_address" UNIQUE ("alias_address")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_aliases_company_id') THEN
    ALTER TABLE "email_aliases" ADD CONSTRAINT "fk_aliases_company_id" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_aliases_mailbox_id') THEN
    ALTER TABLE "email_aliases" ADD CONSTRAINT "fk_aliases_mailbox_id" FOREIGN KEY ("mailbox_id") REFERENCES "mailboxes" ("id") ON DELETE CASCADE;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "idx_aliases_company_id" ON "email_aliases" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_aliases_mailbox_id" ON "email_aliases" ("mailbox_id");

-- ---------- mailbox_settings ----------
-- Foundation table only in Phase 16A, same reasoning as email_aliases
-- above -- one row per mailbox, created lazily on first write, not
-- automatically alongside the mailbox.
CREATE TABLE IF NOT EXISTS "mailbox_settings" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "mailbox_id" integer NOT NULL,
  "signature" text DEFAULT NULL,
  "auto_reply_enabled" boolean NOT NULL DEFAULT FALSE,
  "auto_reply_message" text DEFAULT NULL,
  "timezone" varchar(64) DEFAULT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_mailbox_settings_mailbox_id" UNIQUE ("mailbox_id")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_mailboxsettings_mailbox_id') THEN
    ALTER TABLE "mailbox_settings" ADD CONSTRAINT "fk_mailboxsettings_mailbox_id" FOREIGN KEY ("mailbox_id") REFERENCES "mailboxes" ("id") ON DELETE CASCADE;
  END IF;
END $$;
`;

const EXPECTED_TABLES = ["email_domains", "mailboxes", "email_aliases", "mailbox_settings"];

async function tableExists(tableName) {
    const [rows] = await platformPool.query(
        `SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = ? LIMIT 1`,
        [tableName]
    );
    return rows.length > 0;
}

async function run() {
    console.log("Add email platform tables -- checking platform database...\n");

    const before = {};
    for (const table of EXPECTED_TABLES) {
        before[table] = await tableExists(table);
    }
    console.log("  Before:", before);

    if (Object.values(before).every(Boolean)) {
        console.log("  [skip] all four tables already exist");
        await platformPool.end();
        console.log("\nMigration completed (nothing to do).");
        return;
    }

    // Raw driver, not the ?-placeholder compat wrapper -- this is a
    // static, parameter-free multi-statement DDL block, executed via
    // PostgreSQL's simple query protocol (same mechanism `psql -f`
    // and _setup_platform_db.js use), which is what allows each
    // DO $$ ... END $$ block to be sent correctly alongside the
    // CREATE TABLE/INDEX statements around it.
    await platformPool.nativePool.query(EMAIL_PLATFORM_TABLES_SQL);

    const after = {};
    for (const table of EXPECTED_TABLES) {
        after[table] = await tableExists(table);
    }
    console.log("  After:", after);

    for (const table of EXPECTED_TABLES) {
        if (!after[table]) {
            throw new Error(`Migration did not create expected table "${table}".`);
        }
    }

    console.log("  [done] email_domains, mailboxes, email_aliases, mailbox_settings present");

    await platformPool.end();
    console.log("\nMigration completed.");
}

if (require.main === module) {
    run()
        .then(() => process.exit(0))
        .catch((error) => {
            console.error("MIGRATION SCRIPT ERROR:", error);
            process.exit(1);
        });
}

module.exports = { tableExists, run, EXPECTED_TABLES };
